### ISSUE TITLE
[Request] Customize the number of search results

### ISSUE THREAD

**Issue by alex3236** [lin-ycv/EverythingPowerToys#10]
**Describe the solution you'd like**
Add a setting item to customize the number of search results.

**Comment by lin-ycv** [comment]
This is a Powertoys limitation, as far as I'm aware it only allows for checkboxes
this was request for on Powertoys Repo here: https://github.com/microsoft/PowerToys/issues/14267

do you want more results or less? what's the issue with the current setting of 20 results?
