### ISSUE TITLE
🐛 正则表达式中的 “^” doesn't work (regex)

### ISSUE THREAD

**Issue by Nitmi** [lin-ycv/EverythingPowerToys#104]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
如题，在开启 RexEx 的情况下，正则表达式中的首匹配“^”似乎无法在 EverythingPT 中 work。

**Screenshots**
含“^”的正则表达式：
![含^测试](https://github.com/lin-ycv/EverythingPowerToys/assets/114425147/c6d9d60e-2989-4174-8c0f-bb0280bc989c)

去掉上述“^”之后：
![不含^测试](https://github.com/lin-ycv/EverythingPowerToys/assets/114425147/482d48c1-4e43-4da5-b423-9689c5c9cecd)

**Logs (please upload or provide link to you log):**
 [Log_2024-05-20.txt](https://github.com/lin-ycv/EverythingPowerToys/files/15370074/2024-05-20.txt)

**Version:**
 - PowerToy: v0.80.0
 - Everything: V1.4.1.1024 (x64)
 - EverythingPT: v0.80.0.0
 - Windows: 版本	Windows 11 家庭中文版 23H2 22631.3593

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github
 - Everything: official website
 - EverythingPT: Github(ZIP)

**Comment by lin-ycv** [comment]
的確有問題，但我看不出問題在哪，需要時間測試

**Comment by Nitmi** [comment]
很抱歉，我这里问题依旧。
我先测试了 EverythingPT 81 版本，发现不行，又将 PT 升级到了 81 版本，并重启电脑，但还是不行。

**Comment by lin-ycv** [comment]
請改用debug的dll做以下幾個測試
1. 設定中關閉regex, 使用 r: 收尋
2. 開啟設定regex再收尋一次

上傳桌面上的 EverythingPT.log

**Comment by Nitmi** [comment]
**现在完全没有问题了！**

换了 debug 的 dll，不论上面的方法1，还是方法2，都测试正常；
又换回原本的 dll，测试都依旧正常。

不知道是不是我之前的测试有什么问题，总之，都没问题了。
谢谢你对 EverythingPT 的开发！

[EverythingPT.log](https://github.com/lin-ycv/EverythingPowerToys/files/15415186/EverythingPT.log)

**Comment by lin-ycv** [comment]
我不知道這個問題怎麼解決，版本0.80.0.1又壞了，目前測試只有^不行 其他都可以
Not sure where is issue is, it's broken again in 0.80.0.1, it seems that only ^ doesn't work

**Comment by lin-ycv** [comment]
match path 與 regex 有些不相容，這是everything的限制，我這邊沒有辦法處理
https://www.voidtools.com/forum/viewtopic.php?p=67797#p67797
