### ISSUE TITLE
🐛 Crashes with 0.80

### ISSUE THREAD

**Issue by AJolly** [lin-ycv/EverythingPowerToys#105]
I get frequent crashes with 0.8 that I do not with 0.78

**Logs (please upload or provide link to you log):**
 
[2024-05-18.txt](https://github.com/lin-ycv/EverythingPowerToys/files/15370549/2024-05-18.txt)

**Version:**
 - PowerToy: v.0.80.1
 - Everything: 1.5.0.1373a
 - EverythingPT: 
 - Windows: 22635.3575

**Comment by AJolly** [comment]
I take that back, I do get them with 0.80 as well.

**Comment by lin-ycv** [comment]
does this happen with specific files/directory? have you notice if a certain search query causes the issue?




-------------------------- Begin exception --------------------------
Message: Everything Exception
>
>Exception full name  : System.ArgumentException
Exception message    : title cannot be null or empty (Parameter 'title')
Exception stack trace:
   at Community.PowerToys.Run.Plugin.Everything.Everything.Query(String query, Settings setting)+MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Community.PowerToys.Run.Plugin.Everything.Main.Query(Query query, Boolean delayedExecution)
Exception source     : Community.PowerToys.Run.Plugin.Everything
Exception target site: Boolean MoveNext()
Exception HResult    : -2147024809
-------------------------- End exception --------------------------

**Comment by AJolly** [comment]
Given how frequently i see that error, im not sure im searching for anything long.  Is there a debug mode I can run it in to log?

**Comment by lin-ycv** [comment]
> Is there a debug mode I can run it in to log?
Try the new version, if it still crashes, use the debug dll and upload the log that's saved on the desktop

**Comment by qianzyGit** [comment]
我好想也有这个问题,我更新了81版本,依然会导致powertoy crash

**Comment by lin-ycv** [comment]
Please turn on debug option in 81 and provide the desktop logs.

**Comment by lin-ycv** [comment]
@AJolly @qianzyGit can you provide desktop logs after setting the debug option in settings to verbose?

**Comment by qianzyGit** [comment]
[EverythingPT.log](https://github.com/user-attachments/files/15847605/EverythingPT.log)

**Comment by lin-ycv** [comment]
@AJolly @qianzyGit Please test v0.82.0

**Comment by qianzyGit** [comment]
> @AJolly @qianzyGit Please test v0.82.0

It still crashed
[Uploading PowerToysReport_2024-07-05-13-30-09.zip…]()

[EverythingPT.log](https://github.com/user-attachments/files/16105219/EverythingPT.log)

**Comment by lin-ycv** [comment]
@qianzyGit can you provide the log from `%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs\0.82.0.0`
Other than you being unable to get a response from github, I don't see any meaningful errors from your `EverythingPT.log, it's happening somewhere I'm not logging (or it's straight up crashing everything).

Sidenote: maybe try disabling the update feature I don't think it's the issue, but worth a try?

When it crash, does Powertoys run still work? or does the whole thing crash?

**Comment by qianzyGit** [comment]
[2024-07-04.txt](https://github.com/user-attachments/files/16107810/2024-07-04.txt)
[2024-07-05.txt](https://github.com/user-attachments/files/16107811/2024-07-05.txt)
When it crashes, powertoys won't work.

**Comment by lin-ycv** [comment]
> [2024-07-04.txt](https://github.com/user-attachments/files/16107810/2024-07-04.txt) [2024-07-05.txt](https://github.com/user-attachments/files/16107811/2024-07-05.txt) When it crashes, powertoys won't work.

I see some errors and exceptions, but based on these logs, I don't see anything that's related to EPT... can you disable all plugins other than EPT to make sure the crash is from EPT and not something else?
