### ISSUE TITLE
EverythingPT installer flagged by anti-virus

### ISSUE THREAD

**Issue by tristansly** [lin-ycv/EverythingPowerToys#110]
Malwarebytes is quarantining EverythingPT in the temp folder🐛 xx

**To Reproduce**
Start machine

**Expected behavior**
Nothing?

**Screenshots**
![ZbchW8d6tM](https://github.com/lin-ycv/EverythingPowerToys/assets/15840055/a7a9075f-3fc6-4bb6-9703-54673bf5d2c3)

**Comment by lin-ycv** [comment]
Exe or zip? Nothing I can do about the exe file.

**Comment by tristansly** [comment]
really? idk just letting you know.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by lin-ycv** [comment]
this happens after you press yes on the update dialog correct? that's the exe file.

There's nothing I can do about this, the main issue is that I don't have a digital certificate to sign the exe file, as certs costs hundreds of dollars per year. 
Most AV will flag exe files as potentially dangerous if:
A) it's not commonly downloaded
B) it's not digitally signed

For EPT both cases are true, so many will flag it as dangerous.
Either you trust it and press allow, or you use the ZIP file instead.

**Comment by Anamon** [comment]
Just as a note, yesterday's installer for v0.86.0 is now also flagged by Microsoft Defender (definition `Trojan:Script/Wacatac.H!ml`).

No doubt, the `ml` means this was "detected" by an "AI". I wonder if these snake oil vendors realise what kind of damage they're doing to the security awareness of the public at large. This GenAI nonsense in security software has led to such an unfathomable torrent of bogus detections, that most people have reached the point where any alert is automatically considered to be a false positive by default… </rant>

**Comment by f22raptorroland** [comment]
Detailed report from [Hybrid-Analysis](https://hybrid-analysis.com/sample/52d303fe985ce2bc3476c56234236588cf1b17c2d28352d2ce39761fd39b637a?environmentId=160)
@lin-ycv

**Comment by lin-ycv** [comment]
@f22raptorroland 
Like I said before, there's not much I can do, addressing the suspicious indicators with higher relevnace:
* **Dropped file has high entropy**: compressed png images
* **Drops executable files** || **Writes a PE file header to disc**: extracting EPT and everything dll files to disk
* **Calls an API typically used for keylogging**: not sure why the installer is monitoring `shift`, `1`, `2` and `4` keys, NSIS is probably using it for when there's a popup window.
* **Marks file for deletion** || **Opens file with deletion access rights**: I don't know what `nszFF45.tmp` is, probably something NSIS needs for extraction
* **CRC value set in PE header does not match actual value**: `Everything64.dll` is from Everything's SDK, I have no control other it.
* **Timestamp in PE header is very old or in the future**: have no idea why that date is from the future, these files are compiled by VS

Summary: basically most of the triggers are things from NSIS or Everything's dll file, neither of which I have control over.

**Comment by gabriel-vanca** [comment]
I'm also getting a virus alert from Microsoft Defender, but it's a different signature.
I wasn't getting any errors with the previous versions.

![image](https://github.com/user-attachments/assets/3b9fd18e-2417-4a37-8347-930391b00b8b)

**Comment by EazyCheeze1978** [comment]
Chiming in I got this notification from Defender as well, the Wacatac.h!ml thing. So the consensus is that this is a false positive detected by AI/heuristics? Okay, that does make me feel better. I couldn't imagine not having Everything at a moment's notice :) Thank you for this plugin - I do appreciate it greatly!

**Comment by SoCuul** [comment]
@lin-ycv You could potentially look into Azure Trusted Signing. It's pretty new, but it provides signing certificates for only $9.99 per month. https://azure.microsoft.com/en-us/products/trusted-signing

**Comment by Anamon** [comment]
> Chiming in I got this notification from Defender as well, the Wacatac.h!ml thing. So the consensus is that this is a false positive detected by AI/heuristics? Okay, that does make me feel better. I couldn't imagine not having Everything at a moment's notice :) Thank you for this plugin - I do appreciate it greatly!

Yes; also, it only applies to the installer, not any of the files it installs. If you're worried, as lin-ycv mentioned earlier, you can extract the ZIP file into the PowerToys Run plugin directory to get the same effect without any warning.

**Comment by tristansly** [comment]
Hey this is off topic but do you guys have anything that gives you search results within the flow window? I had the Google search Plus extension and that used to work but I don't want to search through Google and it stopped working. Looking for something that returns web results within the flow window

**Comment by tristansly** [comment]
Also I had a wacatac infection and it was no joke lol. Freaking pain in the beehive
