### ISSUE TITLE
Stop creating log file on the Desktop

### ISSUE THREAD

**Issue by Dominiquini** [lin-ycv/EverythingPowerToys#111]
**Is your feature request related to a problem? Please describe.**
This plugin is always creating a log file on my desktop named "EverythingPT.log" with the text "Checking Update...Done"!

**Describe the solution you'd like**
I don't thing this should happens in production! Maybe put this log on the Temp folder!

**Describe any research you've done**
None.

**Additional context**
Applications shouldn't pollute the desktop with random logs!

Thanks.

**Comment by lin-ycv** [comment]
Reinstall 81.0.1, that'll solve the issue.
