### ISSUE TITLE
💡 Want to add default filter settings

### ISSUE THREAD

**Issue by pzhren** [lin-ycv/EverythingPowerToys#115]
**Is your feature request related to a problem? Please describe.**

For example, you can directly reference the filter settings in everything, like everythingbartools, without entering additional regular expressions.
Similar to the following
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/34993251/6d5737c0-0916-4fdb-b766-f507e40988d4)

**Describe the solution you'd like**

**Describe any research you've done**
I'd appreciate it if you could include some research on the possible methods of implementation or reasource references that'd help me implement your feature request.
If you're unsure if this feature is even plausible to implement, maybe use the discussions instead of a feature request.

**Additional context**

**Comment by lin-ycv** [comment]
Sorry, but you need to be more precise in what exactly you want, I don't use everything toolbar, and i don't understand what the screenshot means, you highlighted "use everything filters" and "remember past rules"

EPT already uses everything filters
what does remember past rules do?

**Comment by a13ph** [comment]
@pzhren to use one of Everything filters type the name of the filter with colon immediately afterwards, like `video:` or 'books:' (as an example of a custom 'books' filter'. Obviously add your prefix for Everything which you have set up in PowerToys.Run.
Case does not matter, `video:` and `Video:` both work the same.

@lin-ycv maybe they want smth like a option to preserve everything's Home setting page, or at least filter pre-selection?
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/577817/dc6d293a-ee23-485c-9171-9882c5298b09)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/577817/fd02ffe6-7d9c-4b63-9c1f-63c408a60ed5)

Personally I think that alternatively or additionally, autocompletion of those filter names might be nice, maybe as a separate plugin/keyword, like
`ef vid` to search for filters (where `ef` is the supposed new keyword to search for filters in Everything)
there choose `videos` from the list of matching filters and maybe code it to auto-match on single result
and then input transforms into 
`e videos:` (where `e` is the user-defined keyword for Everything).
IDK if there is a simpler way to achieve that, I have not found anything for in any way similar behavior in the Everything docs.

**Comment by lin-ycv** [comment]
I thought preselection is what they wanted based on their previous comment https://github.com/lin-ycv/EverythingPowerToys/issues/79#issuecomment-2152334083 , but then they posted a feature request that seems to ask for something else. 

Auto Complete could be implemented, but how it works will need some thought. Ie: Auto Complete shows up as a result you can you down arrow to select from, but that'll reduce the visible actual results, and what should happen if you click the result?

**Comment by a13ph** [comment]
yeah, because i did not want result mixing is the reason why i proposed separating filter autocomplete into a different keyword, with separate plugin for that if one plugin cannot easily handle two keywords.

my idea is to replace filter-search query with actual everything-query on confirmation (by click or enter) of filters

**Comment by lin-ycv** [comment]
There's technical limitations around that, replacing the query creates a new search
And as far as I'm aware, selecting a result causes PTR to close and execute a task. 
So the behaviour would be, select a result, PTR closes, I'd then have to write code to trigger PTR again and paste in the filter query. 
I'm not sure if this can be done reliably. 

If this is a feature you'd like to have, please open a new features request or discussion.

**Comment by lin-ycv** [comment]
FR as I understood it has been implemented in 0.82, if it is not what the OP wanted, please reopen and explain more in detail.
