### ISSUE TITLE
🐛 exact: filter does not work with spaces

### ISSUE THREAD

**Issue by mike406** [lin-ycv/EverythingPowerToys#117]
Try something like `exact:"Program Files"` it does not work but is valid when searching in Everything directly

**Comment by lin-ycv** [comment]
Not sure where the issue is, I'll have to find some time to debug
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/155bc659-6560-445d-99c0-bfd751d11c26)

**Comment by mike406** [comment]
It's something with setting `Everything_SetMatchPath(true);` on line 45 in Everything.cs. I commented that line out and exact searches work with quotes around them, so there is a conflict there with enabling that setting.

**Comment by mike406** [comment]
Sent a PR for your review, thanks!
