### ISSUE TITLE
[Request] Set sort method

### ISSUE THREAD

**Issue by Draxy518** [lin-ycv/EverythingPowerToys#12]
The sort order of my results from Everything is very important to me and currently it looks like this plugin is only sorting by date modified descending. Is there any way we can have the sort method be selectable either in the Plugin interface for PowerToys Run itself or by using an alternate version of this plugin?

**Comment by lin-ycv** [comment]
this request is similar to #10, settings some kind of non-boolean (true/false) value for the plugin.
again, this would be a limitation of Powertoys itself, it doesn't have non-boolean options for plugin settings, it has already been request (https://github.com/microsoft/PowerToys/issues/14267), but it doesn't seem to be happening anytime soon.

in the meantime, I'm looking into some alternative solutions, such as using custom JSON setting file, will update the plugin soon.
