### ISSUE TITLE
🐛 写错字了

### ISSUE THREAD

**Issue by CaiHeran** [lin-ycv/EverythingPowerToys#121]
Context Menu（配置选单选项与顺序）下的“身分”应是“身份”。

**Comment by CaiHeran** [comment]
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/51465198/bde2fa05-e45c-4888-8832-962b044c5c81)

**Comment by lin-ycv** [comment]
下一版會修正，謝謝

**Comment by lin-ycv** [comment]
請問你是用哪版? 原始碼裡一直都是 `身份`?
https://github.com/lin-ycv/EverythingPowerToys/blob/9f19e814c5dc60bb59de5717c0fced24b5558c8c/Properties/Resources.zh-cn.resx#L173-L176
