### ISSUE TITLE
存在搜索不了文件夹的问题

### ISSUE THREAD

**Issue by fairy-ju** [lin-ycv/EverythingPowerToys#122]
现象：搜索不了文件夹，只能搜索文件，而在Everything软件里面可以正常搜索到文件夹，希望能修复，谢谢

everything插件版本：v0.81.0.1
powertoy版本：v0.81.1
everything版本：V1.4.1.1024 (x64)

config：
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/84318632/9880d4a0-6ba7-4af1-8a77-f783a73f0537)

**Comment by lin-ycv** [comment]
問題與 #26 一樣？
用folder: 或改變sort 看看

**Comment by fairy-ju** [comment]
谢谢，英文不好没有发现#26已经解答了，抱歉，改完之后果然就能搜到了。
