### ISSUE TITLE
Fail to initialize plugins

### ISSUE THREAD

**Issue by NinhGhoster** [lin-ycv/EverythingPowerToys#123]
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/27909974/decc38f4-5012-4371-967a-c45f6ddca265)

**Logs
[2024-07-08.txt](https://github.com/user-attachments/files/16121636/2024-07-08.txt)

**Version:**
 - PowerToy: 0.82.0
 - Everything: 1.4.1.1024
 - EverythingPT: 0.82.0
 - Windows: 10 22H2

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github/Windows Store/Winget..etc
 - Everything: Installer
 - EverythingPT: Manual

**Comment by NinhGhoster** [comment]
Closed, I installed a wrong version of EverythingPT. Fixed

**Comment by lin-ycv** [comment]
> Im having the same problem here, but i dont witch version i need for it to work.

Look at your task manager, what is your CPU? If it's Intel/AMD you need x64

If your on Qualcomm, it's a bit more complicated, EPT needs to match the version of PowerToys and Everything, if you mix and match ARM64 and x64, you'll get initialization errors. 

If you're not sure, provide PT logs.

**Comment by Josmiti** [comment]
I installed EPT ARM 64 and not x64. Now is working just fine. Thanks!!
