### ISSUE TITLE
🐛 ARM version does not download from Winget

### ISSUE THREAD

**Issue by akamienski** [lin-ycv/EverythingPowerToys#124]
**Describe the bug**
Winget have capability to download specific installer type, either for x64 or ARM. I've noticed that winget downloads x64 version on ARM pc. Please provide that capability to avoid manual fix.

**Expected behavior**
run _winget install lin-ycv.EverythingPowerToys --source winget --silent_ to install ARM version on Windows 11 on ARM or provide seperate package to winget specifically for ARM

**Version:**
 - PowerToys: v0.82.1
 - Everything: n/a
 - EverythingPT: v0.82.1
 - Windows: 11 Pro on ARM

**Comment by lin-ycv** [comment]
Arm in Winget is only added to in 0.82.1, which is still under review https://github.com/microsoft/winget-pkgs/pull/163962

When you run `winget install lin-ycv.EverythingPowerToys --source winget --silent` it's downloading 0.82.0, which doesn't have the configs for arm, only x64.
