### ISSUE TITLE
Powertoys Setting: Waiting for Slower Plugins Needed

### ISSUE THREAD

**Issue by haldi4803** [lin-ycv/EverythingPowerToys#126]
**Describe the bug**
Whenerver you search for something with Everything in PowerToys Run it will NOT select the Search Results but the Calculator (when entering numbers) or other results from other Plugins, even if you set the modificator for results to the highest number.

**Expected behavior**
Should be written in the Installation notes or on the Github frontpage somwehere that the Powertoys Run Setting "Wait for Slower Plugins-Results before selecting frist result" needs to be checked for this Plugin to work correctly.

**Version:**
 - PowerToy: v0.83.0
 - Everything:1.4.1.1026 x64
 - EverythingPT: v0.82.1
 - Windows: 11

 **Installation method (How did you install the following softwares):**
 - EverythingPT: Manual

**Comment by lin-ycv** [comment]
even when i enable `Wait for Slower Plugins` the calculator is still being displayed as the first result
![image](https://github.com/user-attachments/assets/97a2a0ec-a09c-4090-a805-c80aeaf710f0)

this has always been the behaviour for me, i'm under the impression this is the intended behaviour?

**Comment by haldi4803** [comment]
> even when i enable `Wait for Slower Plugins` the calculator is still being displayed as the first result ![image](https://private-user-images.githubusercontent.com/60565737/356684283-97a2a0ec-a09c-4090-a805-c80aeaf710f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjI1MjQsIm5iZiI6MTcyMzIyMjIyNCwicGF0aCI6Ii82MDU2NTczNy8zNTY2ODQyODMtOTdhMmEwZWMtYTA5Yy00MDkwLWE4MDUtYzgwYWVhZjcxMGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE2NTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzY5ZmMwZDZiYTNiOThmNzhhZWExYjUxNzFmNzRlNDg4MTkzNGJmYTJjOTZkYjcwNzJiMTIzYzI4NWE5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDYwkC22s6lnT40TDmqpe7Vuwcufpy7MkVNSWRJVaoA)
> 
> this has always been the behaviour for me, i'm under the impression this is the intended behaviour of Run?

Nonono that is something else!
You need to select the Weight to 100 or 900 in the Everything Plugin first to put the results topmost!
But even if you DO put them Topmost Run will select the Calculator that is showing up first and then moving toward the bottom when everything results start to show up.

**Comment by lin-ycv** [comment]
So can you provide a screenshot of before and after for the issue that you said needs more documentation?
