### ISSUE TITLE
🐛 Failed to load error on powertoys

### ISSUE THREAD

**Issue by arshadmdvr** [lin-ycv/EverythingPowerToys#127]
I tried installing everything for powertoys via winget and the self-extraction package

**Bug Description**
While turning on everything plugin on powertoys, it shows 
![image](https://github.com/user-attachments/assets/d3e504f8-0beb-417f-ac75-a63b82a3152d)

**To Reproduce**
1. Go to 'Powertoys run' on 'powertoys settings'
2. Click on the 'toggle button' in right side of 'everything' in plugins list
3. See error

**Expected behavior**
The error should not appear

**Screenshots**
![image](https://github.com/user-attachments/assets/d584df81-6098-4afb-948c-6b60149cc8f9)

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Version:**
 - PowerToy: v0.83.0
 - Everything: 1.4.1.1026 (x64)
 - EverythingPT: 0.82.1
 - Windows: 11 22635.4010 ni

 **Installation method (How did you install the following softwares):**
 - PowerToys: exe from github
 - Everything: exe from voidtools.com
 - EverythingPT: exe from github

**Comment by lin-ycv** [comment]
That's weird, any chance you accidentally downloaded the ARM64 instead of x64? Winget shouldn't have this issue tho.
do you have a log file for this?

**Comment by arshadmdvr** [comment]
> That's weird, any chance you accidentally downloaded the ARM64 instead of x64? Winget shouldn't have this issue tho. do you have a log file for this?

Thank you for your response.
I tried removing "C:\Users\arsha\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\everything" folder and reinstalling with "EverythingPT-0.82.1-x64.exe" file. The issue persists. So I think its not because of incorrect setup file. 
Log file is attached below
[2024-08-11.txt](https://github.com/user-attachments/files/16574168/2024-08-11.txt)

**Comment by lin-ycv** [comment]
I see that powertoys runs is constantly reloading settings. 
The following keeps getting logged every few milliseconds 

```
Settings were changed. Read settings.
Successfully read new settings.
retryCount=1
```

So maybe try reinstalling powertoys? See if that helps.

**Comment by arshadmdvr** [comment]
Sure i will try. Will it be the problem with latest version of powertoys?

**Comment by arshadmdvr** [comment]
> I see that powertoys runs is constantly reloading settings. The following keeps getting logged every few milliseconds
> 
> ```
> Settings were changed. Read settings.
> Successfully read new settings.
> retryCount=1
> ```
> 
> So maybe try reinstalling powertoys? See if that helps.

Yeah, it worked. Sorry for not trying it earlier—I assumed PowerToys was working fine since the other extensions of PowerToys Run were functioning properly.
