### ISSUE TITLE
Feature Request: Implement Advanced 'Everything' Plugin Features in Flow Launcher

### ISSUE THREAD

**Issue by nanoraptor** [lin-ycv/EverythingPowerToys#128]
I know it's a weird request to make 😅

Context:
I’ve come across the implementation of the 'Everything' plugin in the [PowerToys Run](https://github.com/microsoft/PowerToys/tree/main/src/modules/launcher) repository, and I’m impressed with the way it handles regex and other advanced search syntax. I believe these features would greatly benefit [Flow Launcher](https://github.com/Flow-Launcher), a popular launcher tool with a growing user base.
(There is a implementation of this in the built in explorer plugin but it does not handle regex and other syntax properly)

Why This Matters:

Enhanced Search Functionality: Bringing these advanced search features to Flow Launcher would provide users with more powerful tools to refine their searches.
Cross-Platform Appeal: Users who work across different launchers would appreciate a consistent and powerful search experience, similar to what’s available in PowerToys Run.
Increased User Engagement: Flow Launcher would stand out even more as a versatile tool, catering to both casual users and power users alike.
Proposal:

Reference the PowerToys Run Implementation: The current implementation in PowerToys Run could serve as a blueprint for integrating similar features into Flow Launcher.
Collaborative Development: Perhaps there could be a collaboration or shared effort between the development teams to bring this feature to Flow Launcher, ensuring consistency and quality.
Request:
I would love to see these advanced features ported over to Flow Launcher's plugin, leveraging the strong foundation built in PowerToys Run. This could be a significant enhancement for the Flow Launcher community, providing a seamless and powerful search experience.

**Comment by lin-ycv** [comment]
Maybe do-able?
But I'm not familiar with flow launcher, as I don't use it. 
At first glance it seems a bit convoluted, they have code for both windows index search and everything search in the same module. 

If there's clear instructions on how the code currently works, I might give it a go. But otherwise I don't really have the time to familiarize myself with Flow's code right now.

**Comment by nanoraptor** [comment]
Thanks for considering the request!

I get that Flow Launcher’s code might seem a bit tangled with both Windows Index and Everything search in the same module. If you’re not familiar with the code, it makes sense to get some clear instructions or documentation first. I am not a developer on anyone who knows that much about building softwares

Since I’m a Flow Launcher user and really like the Everything plugin in PowerToys Run, I thought this might be a good place to ask, given your experience with the PowerToys Run plugin. I thought it would be easy to port this into flow launcher. I would love to have a separate everything plugin with the feature set found in PT Run. If you find some time, it’d be awesome if you could look into it. If not, I might take it up in Flow Launcher’s repo to see if the community can help out.

Thanks again for all the great work you do!
