### ISSUE TITLE
🐛 EverythingPT plugin not loading on latest Powertoys V0.83

### ISSUE THREAD

**Issue by Codecity001** [lin-ycv/EverythingPowerToys#129]
**Flight Check**
- [ yes] I'm sure existing (open and closed) don't have duplicates
- [yes ] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**

Tried X64.exe version of EverythingPT but when powertoys run shortcut is launched Everything plugin didn't load and gave the following pop up.

**To Reproduce**
1. Go to 'powertoys'
2. Click on 'powertoys run'
3. Scroll down to 'plugins section and try turning off and on the Everything plugin'

**Expected behavior**
Plugin should load with no errors

**Screenshots**
![image](https://github.com/user-attachments/assets/9ff8e155-4063-42f3-95ff-4fe698133e3c)

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Version:**
 - PowerToy: V0.83
 - Everything: 1.4.1.1026
 - EverythingPT: V0.82.1  
 - Windows: 11

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github/Windows Store/Winget..etc
 - Everything: Void tools
 - EverythingPT: Github releases
[2024-08-17.txt](https://github.com/user-attachments/files/16646682/2024-08-17.txt)

**Additional context**

**Comment by lin-ycv** [comment]
Based on your log, seems like the same problem as #127 
Try reinstalling powertoys.

**Comment by bnrobinson93** [comment]
A reinstall of PowerToys fixed it for me. Thanks!
