### ISSUE TITLE
💡 Add an option to invoke custom commands on search results.

### ISSUE THREAD

**Issue by maratbakirov** [lin-ycv/EverythingPowerToys#130]
I don't really use File Explorer, I normally use "Far Manager" (https://www.farmanager.com/)
I am thinking if that would be possible to open folder search results in the far manager?

I was thinking if there would be an option to add custom commands for folders/paths or simply override a console host for the "open path in console?".

I am happy to try my hands on implementing it myself, as long as it does not go against any general plan for the plugin.

**Comment by lin-ycv** [comment]
Sure, give it a try, if it works create a PR. 
Adding another context menu option to execute custum commands is probably the best option.

**Comment by maratbakirov** [comment]
trying to compile so far.
it seemed that we also need nsis installed

**Comment by maratbakirov** [comment]
I also had to update the import to this 
  <Import Project="..\..\..\..\Common.Dotnet.CsWinRT.props" />
as other plugins do and 
change target framework to 
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
otherwise it would not compile.

**Comment by lin-ycv** [comment]
@maratbakirov have you made a working implementation?
there's a slight typo/bug i want to fix, if you have an implementation, i can push it in the new version together.

**Comment by maratbakirov** [comment]
@lin-ycv hey mate sorry no. I figured out how are we supposed to compile it I think, so i copied this repo under the src/modules/launcher/plugins in the power toys but I struggle to compile the whole thing atm.
first your project supports .net8 and windows from 7 and up and I think power toys requires windows 10.0.2061 (cant remember the exact version on top of my head).
second, power toys themselves give me lots of compilation errors. some are the "security warnings " from nuget but somehoe treated as errors!


i was trying to use visual studio 2022 community edition. which one you are using?
thanks mate.

**Comment by maratbakirov** [comment]
feel free to update what you need i will catch up and pull to my fork. 
but yeah at the moment when i have spare time to look i cant even compile the damn thing!

**Comment by lin-ycv** [comment]
yes, you clone powertoys repo, then clone this repo into `src/modules/launcher/plugins`, detailed steps are in the wiki https://github.com/lin-ycv/EverythingPowerToys/wiki

NSIS isn't strictly needed, it's only there to build the exe package, you can edit PostBuildEvent to remove the commands that calls on NSIS
I'm not sure what net situation is, as i'm using W11
if you initialized the submodules in powertoys solution, there shouldn't be any nuget errors
once the solution is set up properly, you dont need to compile the whole powertoys, can can compile only EPT project.
I'm also using VS 2022 CE
PT may have done some changes since 82.1 that affects compilation

I'll take a look into this feature, if it's not too complex, i'll just implement it alongside the fixes.

**Comment by maratbakirov** [comment]
https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1901-nu1904

I am getting this.. I think i will simply update the powertoys packages to newer version just to make it compile

**Comment by maratbakirov** [comment]
C:\Program Files\dotnet\sdk\8.0.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1162,5): error NETSDK1130: PowerToys.Interop.winmd cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130

have you seen this error before?

**Comment by lin-ycv** [comment]
PT made some changes, instead of having each plugin define their own target versions, it's now a shared property. 
The new code has implemented this feature, and fixed build issues.

**Comment by maratbakirov** [comment]
Thank you very much mate you are a legend I will give it a try ASAP

**Comment by maratbakirov** [comment]
@lin-ycv  by the way winget still seems to have version 0.82 very old one.

C:\Windows\system32>winget search everythingpowertoys
Name                Id                          Version Source
---------------------------------------------------------------
EverythingPowerToys lin-ycv.EverythingPowerToys 0.82.1  winget

C:\Windows\system32>

**Comment by maratbakirov** [comment]
So I am trying to run this new custom command. I have 2 issues with it.
1) I am trying to override the notepad.exe with my command far.exe and I don't think it is doing anything. Is there an option or a switch I forgot to turn on?
2) how can i actually use the custom command? it is in the settings but does not seem to affect anything. when i do search results,  they are opened with the default command still.
I was imagining there would be like a new option or something in the search results. 
thank you!

**Comment by lin-ycv** [comment]
Winget requires manual review, so it takes times to be updated. It's still awaiting review.
https://github.com/microsoft/winget-pkgs/pull/182136

I implemented this in the context menu, as option 6, so first make sure you have 6 in the text input.

Then in the custom program field, you need to provide the path to the exe file of far manager, most likely the full path is required.

Then you'll have to know how your program accepts launch parameters.
Based on this forum post here, I think the argument would be `$P $P`
https://forum.farmanager.com/viewtopic.php?t=5250

When it's properly configured, you can press ctrl+n to launch, or click the new tab icon in the context menu. 

*Screenshots to be added.

**Comment by maratbakirov** [comment]
thank you! adding option 6 for context menu is what I was missing!
