### ISSUE TITLE
🐛 EverythingPowerToys search is incomplete

### ISSUE THREAD

**Issue by HM-Suiji** [lin-ycv/EverythingPowerToys#131]
## Problem Description
When using this plugin, I found that there seemed to be a lot fewer files when searching for files. Compared with the desktop version of Everything, I found that there were indeed a lot fewer files. I think this is due to some flaws in the matching strategy.

## Error example
While using everything, I tried searching for "tsconfig.json" using the search term "tsconfig.". Everything had 2400+ results, which had what I needed.
![image](https://github.com/user-attachments/assets/34b2a0b6-908a-4ab7-b80f-d656ecae9ef3)
<br/>
But when I use this plugin, the search results are only a pitiful dozen. And there is no "tsconfig.json" that I need.
![image](https://github.com/user-attachments/assets/5167b7fb-4baa-47af-b27a-cbcb767cd7ae)

**Comment by HM-Suiji** [comment]
Sorry, I didn't see the max option in the plugin settings. But I think it's not obvious and it might be easier to find if it's in the documentation.

**Comment by lin-ycv** [comment]
documentation added to wiki
https://github.com/lin-ycv/EverythingPowerToys/wiki/Features
