### ISSUE TITLE
🐛 Show More option not working

### ISSUE THREAD

**Issue by codydunne** [lin-ycv/EverythingPowerToys#132]
**Flight Check**
- [X] I'm sure existing (open and closed) don't have duplicates
- [X] I've tried reinstalling PT, Everything, EverythingPT

Note: uninstalling EverythingPT using chocolatey required an extra step of manually deleting a folder.

* `choco uninstall everythingpowertoys`
* `choco uninstall everything`
* Shutdown PowerToys and delete `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\Everything` manually.
* Uninstall PowerToys manually.

**Describe the bug**
The "Show More" option, which is enabled by default, does not appear to actually show a separate result to open Everything with the current query.

**To Reproduce**
1. Open PowerToys Run
2. Type `` ` query``, in this example screenshot `` ` everything.exe ``. I pasted it in to avoid polluting the log with confidential partial matches.
3. See that none of the options provide a separate result.

This also occurs with queries with many more entries, including more than the 10 default max of the plugin.

**Expected behavior**
I would expect a separate result to open Everything with the current query.

**Screenshots**
![2024-10-08T135553_800x509_Prestigious-Blackrhino](https://github.com/user-attach

ments/assets/70c1108b-7f6e-46bd-9a1d-327842a0bd2c)

**Logs (please upload or provide link to you log):**
[2024-10-08.txt](https://github.com/user-attachments/files/17297559/2024-10-08.txt)
[EverythingPT.log](https://github.com/user-attachments/files/17297560/EverythingPT.log) from verbose mode

**Version:**
 - PowerToy: 0.85.1.0
 - Everything: 1.4.1.1026 (x64)
 - EverythingPT: 0.82.1 
 - Windows: Microsoft Windows NT 10.0.22631.0

 **Installation method (How did you install the following softwares):**
 - PowerToys: GitHub [PowerToysUserSetup-0.85.1-x64.exe](https://github.com/microsoft/PowerToys/releases/download/v0.85.1/
 - Everything: `choco install everything`
 - EverythingPT: `choco install everythingpowertoys`

**Additional context**
N/A

**Comment by lin-ycv** [comment]
There's a bug for `show more` when you're using everything 1.4, manually put in the path to everything.exe that's in program files folder. It should work then.

**Comment by codydunne** [comment]
Awesome, that worked! I used `C:\Program Files\Everything\Everything.exe` without quotes.
