### ISSUE TITLE
The latest version of the plug-in shows everything is not started when it runs

### ISSUE THREAD

**Issue by MickeyCho630** [lin-ycv/EverythingPowerToys#136]
PowerToys and everything are started, but when I run powertoys run, it reminds me how to solve the problem that everything is not running. The version of PowerToys is 0.85.1, and the version of everything is 1.5a. The Windows version is Windows 11 Professional 24H2
![image](https://github.com/user-attachments/assets/0aba90d1-6e87-4e26-a5db-d9f16a437e15)
![image](https://github.com/user-attachments/assets/87cc8fbb-acd0-43b4-b159-2f3bca559bc4)

**Comment by MickeyCho630** [comment]
The everythingPT version is 0.85.1

**Comment by lin-ycv** [comment]
1. Did you disable alpha instance for 1.5a? Is it installed in the default directory? Portable version?
2. It's unlikely, but try to close and restart powertoys without closing everything. If powertoys is launched before everything, powertoys might not see everything.

**Comment by MickeyCho630** [comment]
After the installation, only the language was modified without any Settings, the installation path was the default path, and both software had tried to restart, including the computer had also restarted.

![image](https://github.com/user-attachments/assets/b20b7450-cd2a-47de-a2ba-b9d192452ece)


> 1. Did you disable alpha instance for 1.5a? Is it installed in the default directory? Portable version?
> 2. It's unlikely, but try to close and restart powertoys without closing everything. If powertoys is launched before everything, powertoys might not see everything.

**Comment by MickeyCho630** [comment]
![image](https://github.com/user-attachments/assets/6d28dcd3-f56a-4a70-9f48-b1626542ba32)

**Comment by lin-ycv** [comment]
set alpha_instance to false, that'll fix the issue.
Follow the steps here: https://github.com/lin-ycv/EverythingPowerToys/issues/74#issuecomment-1925755705

**Comment by OrinZ** [comment]
I'm glad this question was asked. I had this exact same issue and fixed it completely by setting alpha_instance (under advanced settings) to false. 

I thought it might be helpful to explain what the setting is -- the standard version of Everything (currently 1.4) only allows one instance of the program to be run at once. This setting exists to mark your 1.5 installation as different, so you can run both at the same time. If you happen to be using 1.4 and 1.5 for some reason, this may interfere with that functionality. I'd recommend choosing one or the other, if you find yourself in that situation.

**Comment by kcollett** [comment]
I'm perhaps completely confused about this. I'm seeing the "Everything is not running" message out of PT Run, but I don't see any advanced options in Everything (and the window title is simply Everything). I installed Everything Lite if that is pertinent.

**Comment by lin-ycv** [comment]
> … I installed Everything Lite …

Lite version does not work, you'll need to use the full or portable version.
https://github.com/lin-ycv/EverythingPowerToys/wiki#prerequisites

**Comment by kcollett** [comment]
Thank you! That fixed the problem.

**Comment by Theistic-guy** [comment]
@lin-ycv I have downloaed the latest verision 1.4 portable version of everything and extracted the zip file of plug-in into that folder of powertoys as mentioned in the installation guide . I am getting the same "Everything not installed" , I put the exe path into the settings of powertoys run in the filed "Everything64.exe" but still no success.

P.S : When I restarted the powertoys after the zip installation of everything plug-in , it prompted me to download Everything64.dll which I chose to be yes. Dunno if it has to do something relevant here .

**Comment by steshinoki** [comment]
> We can also check "start everything on system startup"

This is what was missing from mine. (Also version 1.4, also asked to download Everything64.dll)
