### ISSUE TITLE
🐛 Complex Query Prefix + Show More => Error Dialog with Wrong Search Term

### ISSUE THREAD

**Issue by SVNKoch** [lin-ycv/EverythingPowerToys#138]
(fix at the end)

**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [ ] I've tried reinstalling PT, Everything, EverythingPT
**(Nope, as I literally just installed all 3 😄 )**

**Describe the bug**
When I open the "See more..." PTR result, Everything opens but with the wrong query and gives the following error:
`Unable to open file list: ... is not a valid file list.`
or
`Unable to open file list: C:\Program Files\PowerToys\... is not a valid file list.`

**To Reproduce**
1. Enable Show More
2. Set Query Prefix to something containing spaces and qoutes, e.g. `not:(path:C:\Windows | path:"C:\Program Files") `

**Expected behavior**
When searching for "xyz" and opening more results the Everything querey should be `not:(path:C:\Windows | path:"C:\Program Files") xyz`

**Screenshots**

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Version:**
 - PowerToy: 0.85.1
 - Everything: 1.4.1.1026
 - EverythingPT: v0.85.1.0
 - Windows: 10

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github
 - Everything: exe
 - EverythingPT: ptr

**Additional context**
The bug happens in this line: https://github.com/lin-ycv/EverythingPowerToys/blob/main/Everything.cs#L112
Instead of passing in the query as is, it should:
1. replace all `"` within the query with `""`
2. prefix and postfix the query with `"""` (so `"""query"""`)

This will then open Everything with the correct query without errors.
(I didn't create a PR as I'm not familiar with C# and have no IDE set up for it etc.)

**Comment by lin-ycv** [comment]
I have seen that issue once before, but I can't reproduce it on my computers.

While testing this, I've also noticed another bug, where the query seems to not match entered query
![demo](https://github.com/user-attachments/assets/e7bc21cb-fd65-412d-8e7d-776294833ab9)

I'll do some more tests to figure out what the issue is.

**Comment by SVNKoch** [comment]
Thanks, I can confirm it is now fixed for me as well! 👍
