### ISSUE TITLE
[Request] 好像不能支持 exe:  zip: 等 操作

### ISSUE THREAD

**Issue by xtsteven** [lin-ycv/EverythingPowerToys#14]
目前下面这些操作不支持，希望能得到支持。
因为无法像everything本体一样有菜单选项，所以下面的这样的搜索操作就成了必须支持的功能点
audio: | 搜索音频文件。
zip: | 搜索压缩文件。
doc: | 搜索文档文件。
exe: | 搜索可执行文件。
pic: | 搜索图片文件。
video: | 搜索视频文件。

**Comment by lin-ycv** [comment]
問題在 Everything 的 SDK 好像沒有開放 macro 搜尋
會需要我自己寫這個邏輯，但就可能會與Everything的結果有些不一樣
可以先暫時用 *.zip 的方式搜尋

**Comment by lin-ycv** [comment]
@xtsteven [Everything-0.58.0.Rev2-x64.zip](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.58.0/Everything-0.58.0.Rev2-x64.zip) 有新增了此功能
