### ISSUE TITLE
🐛 Query Prefix being prepended to query after navigating results with arrow keys (prefix stackes)

### ISSUE THREAD

**Issue by SVNKoch** [lin-ycv/EverythingPowerToys#140]
**Is your feature request related to a problem? Please describe.**
I have a Query Prefix defined. And Query Text Disabled, I would therefor assume that my input query is not changed.
When I search for "? ext:png" with "?" being my Search symbol, I get some results.
Now I'm using the arrow keys to find what I'm looking for. When I now notice that it is not part of my list I may decide to change the query, however by now my query is super long as navigating with my arrows keys prefixed the Query Prefix to the search.

**Describe the solution you'd like**
An Option to disable above behaviour => I can navigate with arrow keys and my input stays as "? ext:png".

**Describe any research you've done**
Try with and without the option Query Text

**Additional context**
v0.86.0.0

**Comment by lin-ycv** [comment]
OK, i see the issue you're talking about, this isn't the intended behaviour
![error](https://github.com/user-attachments/assets/a61c3832-1caf-406d-ad4d-a7da54e1b980)
