### ISSUE TITLE
🐛 xx

### ISSUE THREAD

**Issue by roubilibo** [lin-ycv/EverythingPowerToys#142]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
I didn't find the file when searching using powertoys run, but the file was searched when opened directly in everything

**To Reproduce**
1. search file 

**Expected behavior**
display file on powertoys run using everything plugin

**Screenshots**
from powertoys
![image](https://github.com/user-attachments/assets/8e3c97cb-ca60-43c9-a81d-905cf10be280)
from everything
![image](https://github.com/user-attachments/assets/bafde3ab-762d-44d1-8e4a-928df120662c)

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs

**Version:**
 - PowerToy:0.86.0
 - Everything:15a
 - EverythingPT: latest
 - Windows: 11 24H2

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github
 - Everything: installer
 - EverythingPT: winget

**Additional context**

**Comment by lin-ycv** [comment]
What is your EPT setting in the settings panel? Do they match what you have in Everything?

It seems like for EPT you're using:
- default sort (name ascending)
- include path: on

While in Everything you're using:
- date modified (descending)
- include path: off

**Comment by roubilibo** [comment]
yes that's right the setting for EPT is as you mentioned. And for Everything, i don't know how to see the include path setting

But by changing the sort to type_name_ascending, I got the result I was expecting
