### ISSUE TITLE
🐛 After configuring the path for Everything 1.5a, it still prompts that Everything is not installed/running.

### ISSUE THREAD

**Issue by easyatm** [lin-ycv/EverythingPowerToys#144]
**Flight Check**
- [ ] I'm sure existing (open and closed) don't have duplicates
- [ ] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
After configuring the path for Everything 1.5a, it still prompts that Everything is not installed, and the log shows "User on Everything 1.4.

**Screenshots**
![屏幕截图 2024-12-05 123316](https://github.com/user-attachments/assets/4e05e365-8791-400a-b7e4-cc1583cc38a6)
![屏幕截图 2024-12-05 123334](https://github.com/user-attachments/assets/6352fdb3-cc1d-4af8-902a-2918e30a8afe)
![屏幕截图 2024-12-05 130059](https://github.com/user-attachments/assets/197763c5-6674-47ac-93e8-44612d54314f)

**Logs (please upload or provide link to you log):**
[2024-12-05.txt](https://github.com/user-attachments/files/18017643/2024-12-05.txt)

**Version:**
 - PowerToy: v0.86.0
 - Everything: 1.5a
 - EverythingPT: 0.86.0
 - Windows: windows11

 **Installation method (How did you install the following softwares):**
 - PowerToys: Github
 - Everything: 
 - EverythingPT:

**Additional context**

**Comment by lin-ycv** [comment]
is Everything running? it needs to be the the full or portable version.
if you're on 1.5a, did you [disable alpha instance](https://github.com/lin-ycv/EverythingPowerToys/issues/74#issuecomment-1925755705)?
the path configuration is only for the [`show more`](https://github.com/lin-ycv/EverythingPowerToys/wiki/Features#show-more) option

if you're using the full/portable version and it is running, it should be able to detect it, if not i'll need to do some tests.

**Comment by easyatm** [comment]
It works now. After disabling alpha_instance, it’s functional. I didn’t notice that this needed to be configured.
