### ISSUE TITLE
🐛 Not showing in Powertoys settings

### ISSUE THREAD

**Issue by yaboidillon** [lin-ycv/EverythingPowerToys#145]
**Describe the bug**
EverythingPT doesn't show up in the Powertoys Settings GUI. I downloaded the .exe installer, and I have confirmed it created files at C:\Users\Dillon\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything . But it does not show up in powertoys. I've tried closing powertoys and relaunching it.

**Comment by lin-ycv** [comment]
Does any errors pop up?
 Please provide logs.

**Comment by yaboidillon** [comment]
No errors. Where would I find logs?

**Comment by lin-ycv** [comment]
`%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs`

**Comment by yaboidillon** [comment]
[2024-12-11.txt](https://github.com/user-attachments/files/18130128/2024-12-11.txt)
[2024-12-12.txt](https://github.com/user-attachments/files/18130129/2024-12-12.txt)
[2024-12-13.txt](https://github.com/user-attachments/files/18130130/2024-12-13.txt)

**Comment by lin-ycv** [comment]
what version of Powertoys and ETP are you using? the logs indicate Powertoys does not recognize EPT. please also provide a screenshot of the contents of the Everything folder the installer installed, it should look like this:
![image](https://github.com/user-attachments/assets/a569d47b-e025-4d1f-8b13-a132f5aa304c)

**Comment by yaboidillon** [comment]
It looks like this:
![image](https://github.com/user-attachments/assets/e0cc064b-f472-43bb-aa5e-c335a632d4e3)
And as far as what version, it's whatever was available on this Github page and on where ya download powertoys, like, as of this week. Fresh install.


**I suspect ETP is actually working as intended. I've realized that when I scroll down, there is a result that says, "search with everything." I was under the mistaken impression that the results directly displayed in the searchbar window in Powertoys Run would be the Everything results. If there is a way to achieve that, let me know.**

**Comment by lin-ycv** [comment]
that is very weird, if you're able to see `Get search result from Everything`, that means the plugin is loaded and working. Can you double check again to see if the settings are there at the very bottom? 
![image](https://github.com/user-attachments/assets/e5dbfb9e-8473-4401-8f76-d817d8f0515d)

results do display directly in the PT Run
![image](https://github.com/user-attachments/assets/61647253-e48c-422d-ac31-86488f295389)

**Comment by yaboidillon** [comment]
Oh yeah no, see this is what I get when I search .txt:
![image](https://github.com/user-attachments/assets/a760305b-7631-450f-b0c6-a8984449a51b)

But like, I do have "search everything", and (upon further consideration) some results which I think are probably from everything:
![screenshot PT Run2](https://github.com/user-attachments/assets/84738efa-0744-4da1-9461-de3f3baec203)

**Comment by lin-ycv** [comment]
So it's working as intended, just other results are showing first. 
For powertoys run settings page, if you scroll down to the very bottom, you should see the settings for this plugin, there you can set priority/score so it the results show up in front.
