### ISSUE TITLE
🐛 Fail to initialize plugins: Everything

### ISSUE THREAD

**Issue by rayedriasat** [lin-ycv/EverythingPowerToys#147]
**Flight Check**
- [x] I'm sure existing (open and closed) don't have duplicates
- [x] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
After installing the update of 0.87, everything plugin seems to be not working, when starting the powertoys, it pops up a message box saying "Fail to initialize plugins: Eerything
Please report the bug to ......."

**To Reproduce**
1. close powertoys
2. open powertoys
5. ` activation command does nothing

**Expected behavior**
` should be able to show me search results

**Screenshots**
![image](https://github.com/user-attachments/assets/57f4ab84-8a67-4fff-a2bb-7a24026094d3)

**Logs (please upload or provide link to you log):**
[PowerToysReport_2024-12-18-11-58-45.zip](https://github.com/user-attachments/files/18175789/PowerToysReport_2024-12-18-11-58-45.zip)

**Version:**
 - PowerToy: 0.87.0
 - Everything: Everything 1.4.1.1026
 - EverythingPT: 0.87.0
 - Windows: 11

 **Installation method (How did you install the following softwares):**
 - PowerToys: Manually using the exe file
 - Everything: using the "Everything-1.4.1.1026.x64-Setup.exe"
 - EverythingPT: initially it was installed using chocolatey, but chocolatey doesn't have the lates 0.87.0 version, it say i have the latest 0.86.0 version. but in powertoys it pops up to update. After installing the update, the plugin seems to not work.
"Everthing" software is working fine btw.

**Comment by rayedriasat** [comment]
64-bit operating system, x64-based processor
Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎12/‎28/‎2023
OS build	22631.4602
Experience	Windows Feature Experience Pack 1000.22700.1055.0

Did I install the wrong version of the plugin?

**Comment by rayedriasat** [comment]
Yup, Solved. installed x64 now it's working fine.
I mistakenly installed arm64.
Thanks a lot

**Comment by lin-ycv** [comment]
so that's the wrong version, you want
[EverythingPT-0.87.0-x64.exe](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.87.0/EverythingPT-0.87.0-x64.exe)

**Comment by selfdocumentingcode** [comment]
I also got this error twice today (two different Windows PCs) after upgrading to v0.87. 
In both cases it was likely because I upgraded EverythingPowerToys to v0.87 while PowerToys itself was still on v0.86.

It would be nice if the EverythingPowerToys installer/update checker would warn against this scenario.

**Comment by AJolly** [comment]
Also it wiped out all of my settings by installing the upgrade.
ps - Would love it if the installer would automatically exit power toys run and then reload it.   I've got I manually exit and restart right now

**Comment by lin-ycv** [comment]
The installer is intentionally dumb so that it doesn't trip antivirus false positives. Previously the installer would do checks and close PT, but it'd trip a quarter to half of the antivirus, so it was made dumb.

**Comment by AJolly** [comment]
Does av get flagged if you  prompt the user to terminate the process and try again?  

Or use HKLM\System\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations and just tell the user it'll be upgraded next time they reboot.

**Comment by lin-ycv** [comment]
The issue is that AV does't report how exact they're being triggered, especially with ML and AI. 

So I might build version A, minimal trigger, make changes and build version B, but it triggers like everything; remove all the changes to build version C, and C would still trigger, even tho A would be minimal. 

I think you're referring to .msi instead of .exe.
building msi is a bit complex since it's just a wrapper around an exe file, I still need to build an exe first.  

Side note: this is all off topic, so move to discussions if you want to discuss more.

**Comment by Cierra-Runis** [comment]
I was use 0.86.0 of PowerToys and faced the same issue here. After I updating the plugin, the same issue occured. As result, you should also update PowerToys to the latest version 0.87.1.

**Comment by wfurney13** [comment]
> I was use 0.86.0 of PowerToys and faced the same issue here. After I updating the plugin, the same issue occured. As result, you should also update PowerToys to the latest version 0.87.1.

I had the same issue, but after updating PowerToys and then updating the Everything plugin from a previous version, the arm64 version was installed (even though I previously had the x64 version installed). I had to delete the plugin and reinstall the x64 version.
