### ISSUE TITLE
Windows detects Trojan:Win32/Wacatac.B!ml after downloading EverythingPT-0.87.0-x64.exe 

### ISSUE THREAD

**Issue by mayerthomas** [lin-ycv/EverythingPowerToys#148]
Windows detects Trojan:Win32/Wacatac.B!ml after downloading EverythingPT-0.87.0-x64.exe 

The detection occurs both after manually downloading the file and when attempting to update the plugin via PowserToys itself.

**Version:**
 - PowerToy: 0.87
 - Everything: 1.4.1.1026
 - EverythingPT: 0.8.7
 - Windows: 11 24 H2

**Comment by lin-ycv** [comment]
dup of #110

**Comment by mayerthomas** [comment]
Sorry for the duplicate.
