### ISSUE TITLE
[BUG]Failed to load everything plugin

### ISSUE THREAD

**Issue by Hitmanforrent** [lin-ycv/EverythingPowerToys#16]
**Describe the bug**
Failed to load plugin

**To Reproduce**
1. Go to Powertoys Run settings
2. Enable Everything plugin
3. See error.

**Screenshots**
https://i.imgur.com/cxjR1e2.png

**Logs (please upload or provide link to you log):**
[Powertoys Error Log 2022-05-22.txt](https://github.com/lin-ycv/EverythingPowerToys/files/8750771/Powertoys.Error.Log.2022-05-22.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.58.0
 - Everything: 1.4.1.1015 (x64)
 - Windows: 21H2

**Additional context**
Occurred after attempting to update to 0.58.0 revision 2 of the plugin. I've attempted doing a clean install of Powertoys, but haven't had success.

**Comment by lin-ycv** [comment]
@Hitmanforrent  Can you please use this debug version of the plugin and upload the `debugLog.txt` it creates in the Documents folder
[Everything0580-DEBUG.zip](https://github.com/lin-ycv/EverythingPowerToys/files/8675322/Everything0580-DEBUG.zip)

Inside that log file it should look something like
```
EverythingSetup Started
FlagsSet
Reading Custom Settings
# This is the settings file to override the behaviour for "Everything for PowerToys"
# to override a setting, uncomment that line by uncommenting and changing the value
# ie: "# max = 20" -> "max = 10"

# Set max amount of results to return [default: 20]
# max = 20

# Set result sorting method [default: 14]
# https://www.voidtools.com/support/everything/sdk/everything_getsort/
# sort = 14

# There are no more override options
# Restart of powertoys is needed if values are changed
Custom FIN

Get Icons
Got Keys: 6917

rkFileType : HKEY_CLASSES_ROOT\.appcontent-ms
defaultValue : ApplicationContent
Default : NULL
Program : HKEY_CLASSES_ROOT\ApplicationContent\shell\Open\command
System.NullReferenceException: Object reference not set to an instance of an object.
   at Community.PowerToys.Run.Plugin.Everything.NativeMethods.GetFileTypeAndIcon()
```

**Comment by lin-ycv** [comment]
@Hitmanforrent sorry for the delayed reply, been testing different solutions, but I really got no idea what the issue is.
Can you test this version: [Everything05802WIP.zip](https://github.com/lin-ycv/EverythingPowerToys/files/8785919/Everything05802WIP.zip)
In this WIP version I've cleaned up the code for the section that's throwing the exception.

If this version works fine, I'll finalize it into revision 3.
If this version doesn't work, please upload the `Powertoys Error Log` this WIP version creates

**Comment by Hitmanforrent** [comment]
> 

That's alright! Thank you for responding.

The WIP version works fine, thank you so much.

**Comment by lin-ycv** [comment]
Great! I'll test it a bit more just in case, hopefully I can finalize it by next week.
you can use the WIP in the meantime, there's basically no difference between WIP and Revision 2 (functionally speaking), will be different than the planned R3 tho, planning to add translations.

**Comment by lin-ycv** [comment]
FYI, R3 has been released,
