### ISSUE TITLE
[Request] Create a Chocolatey package for each release

### ISSUE THREAD

**Issue by henkisdabro** [lin-ycv/EverythingPowerToys#18]
**Is your feature request related to a problem? Please describe.**
Using Chocolatey religiously for new computer installs and update management I get Everything Search and Powertoys installed automatically, but not this great plugin as it requires manual download, unzip and config within Powertoys' settings.

**Describe the solution you'd like**
It would be fantastic to be able to auto-install this amazing plugin via a chocolatey package for automatic installation. Using a github action to automatically create and maintain the chocolatey package could be possible too. https://community.chocolatey.org/packages?q=everything

**Comment by lin-ycv** [comment]
Hi @henkisdabro , thanks for the request.
I'm currently quite busy with other things until Sept, and have limited time to work on this project.
I'll put this on my todo list for Sept, but I welcome anyone else to work on this before then.

**Comment by lin-ycv** [comment]
it's been summited here, pending mod:
https://community.chocolatey.org/packages/everythingpowertoys/0.59.1

Regarding github actions to maintain the package, it would be great if you could provide some sources or instructions for that.

**Comment by henkisdabro** [comment]
Thanks for the update and your efforts! Unfortunately I don't have experience with how to set up actions, but I thought it could be a possible avenue. I'm not sure how other chocolatey maintainers do this, but I'll let you know if I find anything.
