### ISSUE TITLE
[Request]建议点击搜索结果的“打开所属文件夹”选项能直接定位（选中）相应文件

### ISSUE THREAD

**Issue by a90091343** [lin-ycv/EverythingPowerToys#19]
首先感谢开发者的辛勤付出。目前插件各方面都表现良好，就是缺少点击“打开所属文件夹”按钮后跳转到explorer时自动选中对应文件的功能，希望楼主能够加上。谢谢！

**Comment by lin-ycv** [comment]
will update in the next release (TBD), I'm currently very busy with other things.
