### ISSUE TITLE
调整搜索结果数和搜索范围及显示空结果的bug的问题

### ISSUE THREAD

**Issue by xuangeyouneihan** [lin-ycv/EverythingPowerToys#2]
如题

**Comment by lin-ycv** [comment]
搜尋範圍從Everything裏設定 Tools>Options>Indexes>NTFS/Folders
结果数我是設定5個，要改的話在 NativeMethods.cs 裏改max的數字
https://github.com/lin-ycv/EverythingPowerToys/blob/8d3abd850edfc2f7b044422eff65ecc66c335d9e/NativeMethods.cs#L241
或我晚點再發一個顯示多一點結果的？ 你希望結果有幾個？

**Comment by xuangeyouneihan** [comment]
谢谢，不用了发自我的荣耀手机-------- 原始邮件 --------发件人： "Lin Yu-Chieh (Victor)" ***@***.***>日期： 2022年1月17日周一 12:20收件人： lin-ycv/EverythingPowerToys ***@***.***>抄送： 万里雪飘 ***@***.***>, Author ***@***.***>主    题： Re: [lin-ycv/EverythingPowerToys] 如何调整搜索结果数和搜索范围？ (Issue #2)

搜尋範圍從Everything裏設定 Tools>Options>Indexes>NTFS/Folders

结果数我是設定5個，要改的話在 NativeMethods.cs 裏改max的數字

https://github.com/lin-ycv/EverythingPowerToys/blob/8d3abd850edfc2f7b044422eff65ecc66c335d9e/NativeMethods.cs#L241

或我晚點再發一個顯示多一點結果的？ 你希望結果有幾個？

**Comment by xuangeyouneihan** [comment]
谢谢，麻烦发一个最大结果数和“Community.PowerToys.Run.Plugin.Everything”这个插件一样的或者最大结果数为powertoys允许的最大值的版本。还有一个问题，运行该插件有时会出现最后一个结果只有一个powertoys默认的窗口图标且包括标题在内什么文字描述都没有的情况是怎么回事？（抱歉现在那种情况没发生，也没办法复现）

**Comment by xuangeyouneihan** [comment]
或者这个插件怎么自己编译？我不会😢

**Comment by lin-ycv** [comment]
顯示20個搜尋結果：
https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.1.0/20EverythingForPowerToysRun.zip

我不確定爲什麽會出現一個空的，我測都沒出現過
你試試看20個的這個版本看看

**Comment by xuangeyouneihan** [comment]
谢谢！到时候能在修正完bug的release中再发一下这个20条结果的版本吗？

**Comment by xuangeyouneihan** [comment]
谢谢！到时候能在修正完bug的release中再发一下这个20条结果的版本吗？

**Comment by lin-ycv** [comment]
已修正，請下載新版，預設20個結果

**Comment by xuangeyouneihan** [comment]
谢谢！
