### ISSUE TITLE
[BUG] xx

### ISSUE THREAD

**Issue by Horst12** [lin-ycv/EverythingPowerToys#20]
**Describe the bug**
Search some file and click on Open containg folder icon or Ctrl-Shift-E
An message box "Something went wrong" comes.
See the attache file error.txt

**Expected behavior**
The folder conating the found file should open.

**Screenshots**

**Logs (please upload or provide link to you log):**

**Version (please provide the version of software you are using):**
 - PowerToy: v0.59.1
 - Everything: 1.5.0.1315a
 - Windows: Windows 11 Home x64 21H2 (OS build 22000.778) 

**Additional context**
[Error.txt](https://github.com/lin-ycv/EverythingPowerToys/files/9056870/Error.txt)

**Comment by lin-ycv** [comment]
which version of the this plugin are you using?
this problem was fixed way back in [v0.56.2](https://github.com/lin-ycv/EverythingPowerToys/releases/tag/v0.56.2), I did make some changes in [v0.59.1](https://github.com/lin-ycv/EverythingPowerToys/releases/tag/v0.59.1), but I tested it and works fine on my computers.

**Comment by Horst12** [comment]
Where can I see the version of the plugin ?

**Comment by lin-ycv** [comment]
maybe just download the latest version and see if that throws errors
[v0.59.1](https://github.com/lin-ycv/EverythingPowerToys/releases/tag/v0.59.1)

**Comment by Horst12** [comment]
Downloading version v0.59.1 helped
Shouldn't be an automatic updated when the PowerToys are updated ?

**Comment by lin-ycv** [comment]
I'm a third party developer, so my updates aren't tied to PowerToys, I only update when something breaks or if someone requests a feature.
