### ISSUE TITLE
[Request] Regular expression support

### ISSUE THREAD

**Issue by 2ez4ai** [lin-ycv/EverythingPowerToys#21]
Thanks for your nice tool! I wonder if you can support it with regular expression for file searching?

Everything supports regular expression, so is it possible to add that feature to this plugin?

**Comment by lin-ycv** [comment]
Added here [Everything-0.60.1-x64.zip](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.60.1/Everything-0.60.1-x64.zip)
