### ISSUE TITLE
[BUG]搜索结果没有文件夹以及结果很少？

### ISSUE THREAD

**Issue by bigponglee** [lin-ycv/EverythingPowerToys#23]
为什么我的搜索结果里看不到文件夹之类的，然后搜索结果也比直接用everything少得多。
everything结果：
<img width="624" alt="image" src="https://user-images.githubusercontent.com/43057237/185174277-752d93d0-de04-4c8d-bbe6-4c540919dbe4.png">
插件设置：
<img width="638" alt="image" src="https://user-images.githubusercontent.com/43057237/185174562-fc5e9f06-b43d-4f12-8494-77c6fce87828.png">
power run搜索结果：
<img width="508" alt="image" src="https://user-images.githubusercontent.com/43057237/185174795-24d65c70-de06-4f65-95a8-f25be9ba9f4a.png">

是我打开的姿势不对吗：）

**Comment by bigponglee** [comment]
还有，另一个老的powertoys+everything插件的工作正常[IzaiahSun](https://github.com/IzaiahSun/PowerToys)
![image](https://user-images.githubusercontent.com/43057237/185176106-064758f7-a628-4032-8e7f-16a5f75183b3.png)
，不过里面的插件不支持最新的powertoys

**Comment by lin-ycv** [comment]
請用這個版本測試並再上傳logs
[Everything-Debug.zip](https://github.com/lin-ycv/EverythingPowerToys/files/9375173/Everything-Debug.zip)

**Comment by bigponglee** [comment]
> 請用這個版本測試並再上傳logs [Everything-Debug.zip](https://github.com/lin-ycv/EverythingPowerToys/files/9375173/Everything-Debug.zip)

那么log在哪里呢

**Comment by lin-ycv** [comment]
在powertoys裡輸入
%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs
在最新版本的資料夾裡，上傳最新的檔案
例如:
![image](https://user-images.githubusercontent.com/60565737/185530263-9e61753b-abc8-4d23-8de9-7ff97e132b96.png)

**Comment by bigponglee** [comment]
[2022-08-19.txt](https://github.com/lin-ycv/EverythingPowerToys/files/9378822/2022-08-19.txt)
已上传

> 在powertoys裡輸入 `%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs` 在最新版本的資料夾裡，上傳最新的檔案 例如: ![image](https://user-images.githubusercontent.com/60565737/185530263-9e61753b-abc8-4d23-8de9-7ff97e132b96.png)

**Comment by lin-ycv** [comment]
用Debug版搜尋有結果很少的問題嗎?
我看log都正常，每次收尋都有20個結果

**Comment by bigponglee** [comment]
> 用Debug版搜尋有結果很少的問題嗎? 我看log都正常，每次收尋都有20個結果

问题不在于数量，返回的搜索结果与直接用everything不一致，我试过修改搜索排序，但似乎并没有什么作用，另外就是文件夹结果几乎不出现，即使有同名的文件夹；
ps：能不能直接获取everything搜索结果的前二十个

**Comment by lin-ycv** [comment]
sort 改成與 Everything的設定一樣即可
Everything排列方式預設是 1 (名稱由小到大，資料夾先顯示)
外掛預設14 (最新修改日期先)
settings.toml 有修改後續要powertoys右鍵Exit再重開才會讀取變更

從截圖可見，sort改成1就與everything結果一致
![image](https://user-images.githubusercontent.com/60565737/185546154-177190fb-fad4-49c8-8480-22fda66f9da3.png)
