### ISSUE TITLE
[BUG] 搜索结果很少

### ISSUE THREAD

**Issue by JiunnTarn** [lin-ycv/EverythingPowerToys#25]
**Describe the bug**
与[Issue#23](https://github.com/lin-ycv/EverythingPowerToys/issues/23#issue-1341914605)相同的问题，搜索结果很少，用 Everything 能搜出39个，但用 PowerToys只能搜出1个。

**Screenshots**
![image](https://user-images.githubusercontent.com/45126705/188408542-7d890024-7f61-4ea3-a795-842b9103e606.png)
![image](https://user-images.githubusercontent.com/45126705/188408554-f45a65a4-2161-4f78-86a6-3b4a67c2f678.png)
![image](https://user-images.githubusercontent.com/45126705/188408562-0f9f99cc-f105-4cdc-925d-26700a93f832.png)

**Logs**
[2022-09-05.txt](https://github.com/lin-ycv/EverythingPowerToys/files/9488260/2022-09-05.txt)

**Version**
 - PowerToy: v0.61.1
 - Everything: V1.4.1.1009
 - Windows: Windows11 21H2

**Comment by lin-ycv** [comment]
PowerToys Run 裡有兩個設定，Preview(預覽) 與 Alternative (替代圖示)
先試試看 alternative, 還是有問題的話再試試看preview

**Comment by JiunnTarn** [comment]
> 

👍成功解决了，谢谢！
