### ISSUE TITLE
[BUG] 不支持<>分组操作符

### ISSUE THREAD

**Issue by xuanmi666** [lin-ycv/EverythingPowerToys#27]
在Everything中，分组操作符<>的作用类似于大多数编程语言中的（），用于改变优先级，避免混淆。在EverythingPowerToys中它是不支持的，如果去掉<>，会造成逻辑错误，比如下面的例子：
<*.jpg ceshi1\>|<*.png ceshi2\>
![image](https://user-images.githubusercontent.com/79401279/199977487-f99a580e-aa9a-4084-a9d7-8c7c209a1cca.png)

含义为搜索所有ceshi1文件夹下面的jpg文件和ceshi2文件下的png文件，此时必须加一个<>来区分，如果去掉<>，这个逻辑就不生效了

在Everything中使用正常，本插件中无效

![Snipaste_2022-11-04_20-16-34.png](https://user-images.githubusercontent.com/79401279/199976057-61891e75-d4ad-4b51-a8a7-eb9283665533.png)
![Snipaste_2022-11-04_20-39-16.png](https://user-images.githubusercontent.com/79401279/199976092-8a0d1b20-7500-401a-aab4-0b026b4c4fd9.png)
![Snipaste_2022-11-04_20-43-54.png](https://user-images.githubusercontent.com/79401279/199976140-6023bfc0-cbe4-4a78-a377-b87aa4c3eef9.png)

**Comment by lin-ycv** [comment]
剛發布的新版 修正了，麻煩更新
![image](https://user-images.githubusercontent.com/60565737/200034903-40883131-7075-4d8f-8f5a-ba83af7eace7.png)
