### ISSUE TITLE
增添对搜索以“.”开头的文件或文件夹（如“.minecraft”）的支持及输入句号崩溃的bug

### ISSUE THREAD

**Issue by xuangeyouneihan** [lin-ycv/EverythingPowerToys#3]
如题，之前搜索“.minecraft”，只有一个结果是Minecraft UWP，然后删除原来的搜索内容再输入一个句号，结果PowerToys Run崩溃了，不停弹出报错窗口，电脑基本处于不可用状态。开发者辛苦了！

**Comment by xuangeyouneihan** [comment]
也有可能这就是PT Run的bug而不是这个插件的bug

**Comment by xuangeyouneihan** [comment]
截图：
![image](https://user-images.githubusercontent.com/50788434/149952566-5e2d22a6-268d-46af-88de-89f21e53c69f.png)
![image](https://user-images.githubusercontent.com/50788434/149952604-5d24c43f-d671-46fb-bfb3-07a2f656ad4d.png)
日志：
[2022-01-18.txt](https://github.com/lin-ycv/EverythingPowerToys/files/7889636/2022-01-18.txt)

**Comment by lin-ycv** [comment]
關於搜尋 . 開頭的檔案，這是PTR的限制，非文字開頭會被當成指令，要用Everything搜尋 . 開頭的檔案的話前面先打 @ 再打黨名

關於句點的錯誤，我沒有辦法重現這個錯誤·，我輸入句點不會出錯，我需要時間再做多一點的測試

**Comment by lin-ycv** [comment]
@xuangeyouneihan 如果你在PTR Everything的設定裏將Wait的設定打勾后，打句點還會出錯嗎？

**Comment by xuangeyouneihan** [comment]
会，要不您试试先搜索一个“.”开头的文件之后再删除搜索内容，然后立即关闭搜索框，再呼出搜索框，打一个句号，再往下滚动试试？

**Comment by lin-ycv** [comment]
我怎麼試都無法重現出錯的問題，wait有開與沒開在我的電腦上是沒差
![Untitled Project](https://user-images.githubusercontent.com/60565737/150067557-f0bf1af3-a073-486f-b63b-39d2b3ca0b58.gif)

**Comment by lin-ycv** [comment]
若有其他人有一樣的問題，請讓我知道如何重現
if anyone else is experiencing the same crashing behaviour, please let me know what you did to reproduce the error, as I'm unable to reproduce it from the currently available info.

**Comment by xuangeyouneihan** [comment]
抱歉添麻烦了

**Comment by lin-ycv** [comment]
試了，還是沒有問題

看起來有可能是PT Run的問題:
https://github.com/microsoft/PowerToys/issues/13881

建議你去 PT 發文看看他們怎麼說
我先將這文close掉，有需要的話再reopen

**Comment by xuangeyouneihan** [comment]
您再试试在搜索框里输入一个之前没搜过的中文或者输入简体中文试试？我昨天搜索“作文”两字也报错了

**Comment by xuangeyouneihan** [comment]
@lin-ycv 现在发现真不是句号的问题，并且就是这个插件的原因。我狂按“s”打出了“杀杀杀”，然后按“Breakspace”，删到只剩一个“杀”时它又报错了  
**复现方式：连按同一个键，打出一连串同样的字，然后按住“Breakspace”，删到最后一两个字时自然会崩溃报错**

**Comment by xuangeyouneihan** [comment]
**更正复现方法：在搜索框内输入一个在很多文件的文件名中都有的汉字**  
非常抱歉！现在发现有可能就是PTR的问题😰，我只开启windows搜索也出现了同样的结果。我一会去PowerToys那里提issue看看
