### ISSUE TITLE
[Request] Exclude folders/filters from results

### ISSUE THREAD

**Issue by daniel-richter** [lin-ycv/EverythingPowerToys#30]
Would it be possible to exclude files/folders/filters from the displayed results (without modifiying Everthings's own exclude list)?

**Is your feature request related to a problem? Please describe.**
I know, there is an exclude feature directly in Everything. With "full" Everything, I want to search all files on my computer - but with PowerToys, I do not want to see results from all files and folders on my machine (e.g. AppData, temp, .git, .svn, ...).

**Describe the solution you'd like**
I would like to have the possibility to customize specific Everything for PowerToys filter lists (e.g. in settings.toml).

**Comment by lin-ycv** [comment]
this is a slightly complicated matter depending on the exact behaviour you're looking for.
Are you trying to :
- [ ] A. limit the results to just a few specific folders? or
- [ ] B. to exclude only a few specific folders?

This plugin only packages your inputs and passes it on to Everything, so if you're unable to achieve that query behaviour on Everything it's not possible to achieve in this plugin unless I do some hacky logic (which I'd like to avoid doing).

From what I understood in your request, it seems like you want B; if you're comfortable with named instances, B is simple to achieve without any changed on my side. Set your default instance of everything to work for this plugin (excluding the folders you don't want), then create a named instance for the full index (for your other purposes).

If you want A, you can limit a search using [search options ](https://www.voidtools.com/support/everything/searching/) (which was requested and implemented in #27), some additional info [here](https://www.voidtools.com/forum/viewtopic.php?t=9641) 

 `settings.toml` currently only allow you to create custom extension filters, will have to add some additional code if you'd like to have filters in `settings.toml` to limit the search to just a few specific folder.

**Comment by daniel-richter** [comment]
> From what I understood in your request, it seems like you want B; if you're comfortable with named instances, B is simple to achieve without any changed on my side. Set your default instance of everything to work for this plugin (excluding the folders you don't want), then create a named instance for the full index (for your other purposes).

Great, that's it! [Everything Named Instances](https://www.voidtools.com/support/everything/multiple_instances/) will solve my problem. I can e.g. configure Everything's (default instance) include/exclude behaviour and have another instance with different settings (that will e.g. search all folders on my disk). Thanks!

**Comment by AJolly** [comment]
I'd say extending the custom filters would be very useful - actually is it possible to load/reference a filter you've already created directly in Everything?

**Comment by lin-ycv** [comment]
@AJolly 
the sdk is not fully featured, in the sdk, some filters works (like size:) while some others don't (like pic: exe: ..etc)
Custom filters for the plugin can be defined in settings. toml
As to loading custom filters defined in everything, I'm not sure. If it doesn't work, please open a new issue.

**Comment by commoduskb** [comment]
So, I can exclude certain folders from appearing in Run, even if Everything has them in my index.
Example: Everything index includes folder 1 and 2, but I only want Run results to show 1. 

How can I do this exactly?

**Comment by lin-ycv** [comment]
@commoduskb use the [prefix feature](https://github.com/lin-ycv/EverythingPowerToys/wiki/Features#query-prefix)
Fill in the folder path with an exclamation mark in front of it. 
`!"C:\Program Files\" `
To exclude multiple, just repeat. 
`!"C:\Program Files\" !"C:\Users\" `
Remember to input a single space at the end.
