### ISSUE TITLE
[BUG] 显示不全

### ISSUE THREAD

**Issue by swordnine** [lin-ycv/EverythingPowerToys#31]
文件一多就显示不全

**Comment by lin-ycv** [comment]
不懂，與 #20 有關嗎? 還是有截圖嗎?

**Comment by lin-ycv** [comment]
`Setting.toml` 裡可以設定 `max`, 預設只顯示20個，前面的`#`需要刪掉設定才會被讀取
![](https://user-images.githubusercontent.com/60565737/185546154-177190fb-fad4-49c8-8480-22fda66f9da3.png)

**Comment by swordnine** [comment]
> 外掛資料夾裡 裡可以設定 , 預設只顯示20個，前面的需要刪掉設定才會被讀取`Setting.toml``max``#` ![](https://user-images.githubusercontent.com/60565737/185546154-177190fb-fad4-49c8-8480-22fda66f9da3.png)

感谢，还有一个问题想请教一下。
配置中已经过滤cab等文件，为什么结果还是会显示cab等文件？

<img width="543" alt="2022-11-29_200927" src="https://user-images.githubusercontent.com/61126745/204526097-4354836b-5655-403b-afe4-f2f97c6940ac.png">
<img width="750" alt="2022-11-29_200742" src="https://user-images.githubusercontent.com/61126745/204526107-e741a049-85f1-4472-b37b-b3f0a3ee72b1.png">

**Comment by lin-ycv** [comment]
> 感谢，还有一个问题想请教一下。 配置中已经过滤cab等文件，为什么结果还是会显示cab等文件？
> <img alt="2022-11-29_200742" width="750" src="https://user-images.githubusercontent.com/61126745/204526107-e741a049-85f1-4472-b37b-b3f0a3ee72b1.png">

如果你不希望看到特定檔案類型，需於everything主程式裡設定
Settings裡的filter是用來在使用關鍵字時指定顯示的類型
例如
`Exe: filename` 只會顯示 bat cmd exe MSI msp msu PS1 scr 類型的檔案
