### ISSUE TITLE
Find Folders

### ISSUE THREAD

**Issue by coldice4678** [lin-ycv/EverythingPowerToys#32]
I can only search up individual files, not folders. I would like to be able to search for folders. My Everything settings is set to have folders in my results. 

Additionally, I am unsure what "Path - search path in additional to file/folder name" setting does. I was hoping that was the setting to toggle on and off, but have found no difference in the results with it on or off.

Any help on this would be helpful. And thank you for working on this much needed plug-in, its very appreciated.

**Comment by lin-ycv** [comment]
The reason you don't see folders is because of how the result is sorted, read #26 for more details on how to change sort order.

As for Path, more info here #24 

I'm closing this issue as duplicate, if you have further issues, please reopen.
