### ISSUE TITLE
[Request] Adding "Run as different user" context menu

### ISSUE THREAD

**Issue by htcfreek** [lin-ycv/EverythingPowerToys#35]
**Is your feature request related to a problem? Please describe.**
Sometimes you have to open apps as admin. And in some situations you need to switch the user (when uac is off).

**Describe the solution you'd like**
A new context menu button to invoke the RunAsUser command for application files.

**Describe alternatives you've considered**
_No answer._

**Additional context**
- You can use `Wox.Infrastructure.Helper.RunAsUser(path)`.
- You can find a code example in the program plugin.

**Comment by lin-ycv** [comment]
implemented, but I also upgraded to NET7, so waiting for PT 0.65.0 update before creating release
