### ISSUE TITLE
提示everything is not running

### ISSUE THREAD

**Issue by chenzhixiang111** [lin-ycv/EverythingPowerToys#4]
我的电脑上已经安装了everything，但是当我使用Powertoys Run的时候，它依旧提示我everything is not running
![1644457424(1)](https://user-images.githubusercontent.com/36698937/153321068-a6da7840-ba74-40f8-a63a-d2e9106e3371.jpg)

**Comment by lin-ycv** [comment]
確認一下，你安裝的是installer版的everything，不是portable或lite?

**Comment by chenzhixiang111** [comment]
> 

好吧，我安装的是lite版的

**Comment by Chaoses-Ib** [comment]
补充一下，portable 版本是支持 IPC 的，只有 lite 不支持。另外，Everything 1.5 Alpha 默认会启用命名实例，导致无法进行 IPC，可以添加一句说明，引导 1.5 Alpha 的用户按照 [Disable 1.5a Instance](http://www.voidtools.com/forum/viewtopic.php?f=12&t=9799#instance) 的说明关闭命名实例。
