### ISSUE TITLE
Add support for Everything 1.5a

### ISSUE THREAD

**Issue by neoOpus** [lin-ycv/EverythingPowerToys#40]
**Is your feature request related to a problem? Please describe.**
Everything 1.5a became very stable and many are using it instead of 1.4 as it has way more features, it is not detected though by your plugin.

**Describe the solution you'd like**
please add support to it (it comes with so many additional features). 

**Describe alternatives you've considered**
or allow specifying the path of the executable in your plugin so anyone decides what version they would like to use and many are using multiple versions for several reasons like offline database of a NAS etc that can be specified in .ini file.

**Additional context**
![image](https://user-images.githubusercontent.com/1388336/207577395-0bc60487-923d-4b3b-b4be-d4c20eebe9cc.png)

**Comment by neoOpus** [comment]
BTW, I am aware of the [Disable 1.5a Instance](http://www.voidtools.com/forum/viewtopic.php?f=12&t=9799#instance) and It works this way but what I am after is to make it work in different instances of everything that can have different settings.

**Comment by lin-ycv** [comment]
This plugin uses the SDK provided by voidtools to package your query and send it to Everything, if your feature is not exposed in the SDK, there's nothing I can do. If you provide a specific feature(s) request, I can check if it's exposed and how to implement it.

The SDK library I'm using is signed in 2020, I see the there's one from voidtools signed in 2022, there's no versioning or change log, so I don't know what changed. You can try replacing `Everything64.dll` in `C:\Program Files\PowerToys\modules\launcher\Plugins\Everything`  with the newer version [Everything-SDK.zip/dll](https://www.voidtools.com/support/everything/sdk/) (or [download it here](https://github.com/lin-ycv/EverythingPowerToys/files/10233288/Everything64.zip)), and see if that changes anything.

The SDK does not expose the ability to configure which instance to use, it is hard coded, as seen [here](https://www.voidtools.com/forum/viewtopic.php?f=12&t=9875&p=35767&hilit=multiple+instance+sdk#p35767), `named instances support in SDK` is still under TODO.
