### ISSUE TITLE
[BUG] Setting.Options could be null

### ISSUE THREAD

**Issue by daniel-richter** [lin-ycv/EverythingPowerToys#41]
**Describe the bug**
If `_setting.Options` is null (what it is by default), `ContextMenuLoader.LoadContextMenus` will throw an exception.

**To Reproduce & Version**
Run the plugin(?) with version ef6154b

**Additional context**
When creating a new `ContextMenuLoader`, `_setting.Options` is null or at least could be null.

https://github.com/lin-ycv/EverythingPowerToys/blob/3ec0ddcf1e60a7259093c333cd9d21de70f4da7f/Main.cs#L80

The following code would fail in this case:

https://github.com/lin-ycv/EverythingPowerToys/blob/3ec0ddcf1e60a7259093c333cd9d21de70f4da7f/ContextMenuLoader.cs#L39

**Comment by lin-ycv** [comment]
I'm not getting any exceptions or errors on my side?

On my computers, `UpdateSettings` is executed first on launch of PT, this is before `Init` so `_setting` is never null
https://github.com/lin-ycv/EverythingPowerToys/blob/3ec0ddcf1e60a7259093c333cd9d21de70f4da7f/Main.cs#L135

are you running public release version of PT?
if you're getting exceptions, can you provide log?

**Comment by daniel-richter** [comment]
To clarify: The `Options` property of the `_settings` object is (or can be) null. 

https://github.com/lin-ycv/EverythingPowerToys/blob/3ec0ddcf1e60a7259093c333cd9d21de70f4da7f/Settings.cs#L9-L21

All of the other settings get initialized, but (only) `Options` does not.

**Comment by daniel-richter** [comment]
> In the constructor for `Settings()`, if there's custom settings in the `settings.toml` file, `Options` property is filled out using those settings
> If there's no custom settings for `Options` (aka it's `null`), it's initialized to this hard-coded value

No, not in every case. If there is no `settings.toml` found, the constructor of `Settings` will return immediately and won't initialize any property. So all properties will have their default value from their property definition; `Options` does not have any (so it's null).

https://github.com/lin-ycv/EverythingPowerToys/blob/3ec0ddcf1e60a7259093c333cd9d21de70f4da7f/Settings.cs#L21-L25

**Comment by daniel-richter** [comment]
BTW: Hardcoding the path (resp. the folder) of settings.toml can fail in the following cases:
- The plugin's folder is not named "Everything".
- The base path of the calling executable does not match so "modules\launcher\Plugins" will find the plugins folder.
  (That's what fails in my case. I start PTRun so the path above would resolve to "**\modules\launcher\modules\launcher**\Plugins\Everything\settings.toml")

I would recommend to determine the path as follows:
```cs
string settingsPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "settings.toml");
```

**Comment by lin-ycv** [comment]
ah ok, I see what you mean. will make some changes.
