### ISSUE TITLE
PowerToys complains 『Failed to Load Everything Plugin』

### ISSUE THREAD

**Issue by leoleoasd** [lin-ycv/EverythingPowerToys#43]
I don't know how to extract logs. I'll provide them after I figure this out.

![image](https://user-images.githubusercontent.com/37735580/208832880-25e49d41-f698-4433-b83d-bd3ac8f0d011.png)
![image](https://user-images.githubusercontent.com/37735580/208832960-690c9d9a-d783-4940-afa0-0cf2b8fc401d.png)
![image](https://user-images.githubusercontent.com/37735580/208833007-2777bcd2-6731-4ea4-a5b0-a9d7d93c713f.png)

**Comment by lin-ycv** [comment]
what version of powertoys are you using? I  think you're using an older version of powertoys with a new version of this plugin, generally speaking, version of this plugin should be equal or less than the version of powertoys you have installed.
If your version numbers match, then please provide a log by right clicking on the PoweToys icon on the task bar and click `report bug`, it'll create a log package on your desktop

你使用的 powertoys 是第幾版? 感覺你用了舊版的Powertoys但是裝了新版的插件，差件的版本須等於或低於你安裝的powertoys版本。
如果不是版本問題，請在工具列上的powertoys圖示按右鍵點`report bug`，log 會被打包到桌面上

![image](https://user-images.githubusercontent.com/60565737/208841127-39520bd5-57bd-4aad-abf4-8bcb06ccb53f.png)

**Comment by leoleoasd** [comment]
非常感谢，是版本问题，更新后就好了，我以为二者的版本号是独立的   

感觉可以在安装和release界面提示一下版本号需要match
