### ISSUE TITLE
[Request] Result type priority setting

### ISSUE THREAD

**Issue by Pheggas** [lin-ycv/EverythingPowerToys#46]
**Is your feature request related to a problem? Please describe.**
I just started using PowerToys Run and immediately attached this plugin to it. I love it so far but the one thing i hate is that i can't sort things that i want to display. For example, when i search for program, it shows files first and then the .exe itself.

**Describe the solution you'd like**
I want to customize those priorities to my taste. For example to display .exe files first, then folders, then files and even sort individual file extensions (but that's not a core of this FR)

**Describe alternatives you've considered**
There's none sadly, just to use Search Everything which defeats purpose of EverythingPowerToys

**Additional context**
In Search Everything app for Windows, there's feature that will mark your last selected option (in list of things that the search found) if you already search for that string and opened file / program with it. For example, when i search for program, then select -> open it, and then after some time i will open Search Everything again and search for same string again, it would automatically mark my last selected option. I would like to see that feature in EverythingPowerToys too, in such a form like it would offer my last selected option as the first result in PowerToys Run window.

**Comment by lin-ycv** [comment]
For priority sort, that'd require custom logic that not part of the Everything SDK, but I think you can set the sort to extension name ascending in `settings.toml`, that should give you a similar behaviour to what you're requesting (most of the time)

For the option to keep last selection, I need to go back and check how PTR handles that, I believe the default behaviour of PTR keeps your previous query? 
Not sure about selection, it might be outside the scope of this plugin.

**Comment by Pheggas** [comment]
> For priority sort, that'd require custom logic that not part of the Everything SDK

That's unfortunate. Thanx anyway for nice mapping of possibilities. 

> I believe the default behaviour of PTR keeps your previous query?

That sounds about right.

**Comment by lin-ycv** [comment]
that's an issue on how PTR works, it has been raised before, but because of how PT is set up, it's a bit complicated to implement a solution
https://github.com/microsoft/PowerToys/issues/18693
https://github.com/microsoft/PowerToys/issues/22053

**Comment by Pheggas** [comment]
> that's an issue on how PTR works, it has been raised before, but because of how PT is set up, it's a bit complicated to implement a solution [microsoft/PowerToys#18693](https://github.com/microsoft/PowerToys/issues/18693) [microsoft/PowerToys#22053](https://github.com/microsoft/PowerToys/issues/22053)

I agree to see same issue so it's definitely this one. Thank you for mentioning!
