### ISSUE TITLE
能否支持exe图标自定义展示？

### ISSUE THREAD

**Issue by sweetwisdom** [lin-ycv/EverythingPowerToys#48]
之前下载过一个版本叫`Community.PowerToys.Run.Plugin.Everything`,可以很好的支持exe和apk等图标展示

但是现在这个版本不支持
如下图：

![image](https://user-images.githubusercontent.com/57869305/225813996-2c0803c6-bbec-4df5-a360-d46009c9b616.png)

![image](https://user-images.githubusercontent.com/57869305/225814038-44877622-9299-4f4c-939f-ce625c1361aa.png)

**Comment by lin-ycv** [comment]
開啟Preview選項應該就可以了
![image](https://user-images.githubusercontent.com/60565737/225821282-a41db69a-8aaf-491d-a629-7ce9951edb18.png)

**Comment by sweetwisdom** [comment]
谢谢大佬
