### ISSUE TITLE
[BUG] Sometimes copying file path fails.

### ISSUE THREAD

**Issue by Nitmi** [lin-ycv/EverythingPowerToys#51]
**Describe the bug**
Sometimes copying file path fails.

**To Reproduce**
1. Open Power Toys
2. Search for Files with Everything Plugin Prefix
3. Click on Copy Path icon
4. A pop-up window appears with the prompt `Cannot set the text in the clipboar`, and when checking the clipboard, the desired path to be copied is not found.

**Expected behavior**
Copying file path always successfully without any pop-up window appearing.
**Screenshots**
![Snipaste_2023-05-17_11-23-06](https://github.com/lin-ycv/EverythingPowerToys/assets/114425147/98fc476f-b726-4232-886f-78a67a63f37f)
***
![2](https://github.com/lin-ycv/EverythingPowerToys/assets/114425147/09bd47c4-a082-4143-8f06-80b2eae7fdce)

**Logs**
[2023-05-17.txt](https://github.com/lin-ycv/EverythingPowerToys/files/11494036/2023-05-17.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.69.1
 - Everything: 1.4.1.968
 - Windows: Win11 22H2 22621.1702

**Comment by lin-ycv** [comment]
你有管理剪贴板的軟件嗎? 因為其他軟件正在使用剪贴板所以外掛無法寫入
我研究一下該怎麼處理比較好

**Comment by lin-ycv** [comment]
在我的電腦上我無法呈現這個錯誤，我做了一點微調，但不確定有沒有解決這個問題
麻煩你測看看
[Everything.zip](https://github.com/lin-ycv/EverythingPowerToys/files/11518476/Everything.zip)

**Comment by Nitmi** [comment]
我簡單地測試了一會，現在已經完全不會再出現之前那個問題，感覺非常完美。
感謝你對此插件的開發與改進。
點贊！
