### ISSUE TITLE
[BUG] the latest version of PowerToys changes the plugins folder

### ISSUE THREAD

**Issue by Snoopy1866** [lin-ycv/EverythingPowerToys#52]
**Describe the bug**
The latest version v0.72.0 of PowerToys changes the plugins folder to C:\Program Files\PowerToys\RunPlugins

**To Reproduce**
1. Update the PowerToy to v0.72.0
2. The everything plugins does not work

**Expected behavior**
The everything plugins works as usual.

**Screenshots**
No screeshots.

**Logs (please upload or provide link to you log):**
 There is no need to provide log.

**Version (please provide the version of software you are using):**
 - PowerToy: v0.72.0
 - Everything: V1.4.1.1024 (x64)
 - Windows: Windows 10 Enterprise LTSC 21H2 19044.3208

**Additional context**
Release page guidance should be updated to the new folder of plugins. And there is no need to modify any code.

**Comment by sevenyoung7** [comment]
Thanks a lot! I found it not working after the update to 0.72. So I came here and fortunately got the solution. Now it's solved. Bingo!

**Comment by timothek** [comment]
The chocolatey package also still installs the plugin in the wrong directory. It also needs to be changed to "C:\Program Files\PowerToys\RunPlugins" to work properly.

**Comment by cobrabr** [comment]
I had to place it under `%LOCALAPPDATA%\PowerToys\RunPlugins` for it to work.

**Comment by rombat** [comment]
Thanks ! 👍🏼

**Comment by wangjq4214** [comment]
Thanks ! 

It's worked !

**Comment by alexpbrooks** [comment]
Thanks for sharing this fix

**Comment by lin-ycv** [comment]
@cobrabr 


> I had to place it under `%LOCALAPPDATA%\PowerToys\RunPlugins` for it to work.

did you install PT using per user installer instead of machine wide?

**Comment by cobrabr** [comment]
@lin-ycv Probably. I'll double check and reinstall if necessary. Thanks!

**Comment by nejc-cc** [comment]
I had to place plugin in folder `C:\Program Files\PowerToys\modules\launcher\Plugins`
And I'm on v0.72.0
I didn't even have a folder named "RunPlugins".
