### ISSUE TITLE
[Request] Add powertoys and everything as dependencies in choco package

### ISSUE THREAD

**Issue by shvchk** [lin-ycv/EverythingPowerToys#55]
**Is your feature request related to a problem? Please describe.**
When you install EverythingPowerToys package, no deps are installed, so it doesn't work ootb

**Describe the solution you'd like**
Install dependencies

**Describe alternatives you've considered**
Manual install. Not cool : )

**Comment by lin-ycv** [comment]
Which dependencies are we talking about?

**Comment by shvchk** [comment]
- https://community.chocolatey.org/packages/Everything
- https://community.chocolatey.org/packages/powertoys

**Comment by lin-ycv** [comment]
Ah yes, sorry missed the title. Definitely can do for Choco package, will add it into v0.73.0

**Comment by lin-ycv** [comment]
There seems to be some issue with listing powertoys as a dependency, as it will not install.
I'm removing the powertoys dependency for now until the issue is solved here:
https://github.com/mkevenaar/chocolatey-packages/issues/204

**Comment by lin-ycv** [comment]
As there is no progress/response from the maintainer of the Powertoys package, I can only assume they will not be fixing (or it can't be fixed), so I'm closing this issue for now.
