### ISSUE TITLE
[BUG] results are not aligned with Everthing after setting sort=1

### ISSUE THREAD

**Issue by HardLeft1004** [lin-ycv/EverythingPowerToys#56]
**Describe the bug**
in ver 0.72, setting sort=1 is usefull. After updated to 0.73, it's just not working

**To Reproduce**
like this
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/48342561/9bfa40c8-6142-4069-8d3c-00e184e0a1af)

**Expected behavior**
results are aligned with Everthing

**Version (please provide the version of software you are using):**
 - PowerToy:0.73
 - Everything:V1.4.1.1024 (x64)
 - Windows:win11 22H2

**Comment by lin-ycv** [comment]
Looks fine on my side, did you restart powertoys after changing the value in settings file?
Also i see that you're using regex, make sure to enable it in powertoys settings
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/5c59c6df-06f0-43fc-a320-6b59ce2d45b7)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/e4218ded-e867-4ebb-891e-531436db41c7)

**Comment by HardLeft1004** [comment]
> Looks fine on my side, did you restart powertoys after changing the value in settings file? Also i see that you're using regex, make sure to enable it in powertoys settings ![image](https://user-images.githubusercontent.com/60565737/266914783-5c59c6df-06f0-43fc-a320-6b59ce2d45b7.png) ![image](https://user-images.githubusercontent.com/60565737/266915115-e4218ded-e867-4ebb-891e-531436db41c7.png)
I rebooted my laptop and reinstalled powertoys. Now when I search without using regex, it works fine
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/48342561/6c6e7cd0-1fb3-4bda-b8a5-fd2c5adc4ada)
however, if regex is used, search results differ
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/48342561/e4a7c69b-254f-4412-9681-9565288a72e9)
