### ISSUE TITLE
[Request] Enable control over the update available dialogue popup

### ISSUE THREAD

**Issue by jordantgh** [lin-ycv/EverythingPowerToys#57]
For users who don't feel the need to update frequently, it would be nice to have the option to "Skip this version" or toggle "Search for updates automatically at startup", or ideally both. Especially since all the popup does is take you to the Releases page, there's no reason it should be mandatory for the user to see that.

**Comment by lin-ycv** [comment]
The option to disable update check is in the settings, does unchecking this setting not work for you?
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/cce389e0-41a2-4266-a3fc-8e55b384853e)
