### ISSUE TITLE
PowerToys Run compatibility: Braking changes coming with 0.75.0

### ISSUE THREAD

**Issue by htcfreek** [lin-ycv/EverythingPowerToys#59]
There are two braking changes that come with v0.75.0 of PowerToys Run:
- Each plugin has to provide a static public string property in its main method to provide the plugin id in its code. (https://github.com/microsoft/PowerToys/pull/27468)
- The way of providing the ComboBox list items will change and the items now can get reordered without braking its value. (https://github.com/microsoft/PowerToys/pull/28972)

**Comment by lin-ycv** [comment]
Thanks for the heads-up; will adjust accordingly.
