### ISSUE TITLE
[BUG] PowerToys 0.75.0插件初始化失敗

### ISSUE THREAD

**Issue by Hyunicode** [lin-ycv/EverythingPowerToys#61]
早上將PowerToys更新到0.75.0的版本重啓后提示未能初始化，原因是0.75.0將部分UI接口改了

![image](https://github.com/lin-ycv/EverythingPowerToys/assets/81250265/bb892f01-6cbf-4631-90da-71158c71bf0b)

**Comment by lin-ycv** [comment]
#60 
有以修正的新版，但未發布
