### ISSUE TITLE
[Request] 扩展名白名单

### ISSUE THREAD

**Issue by d0j1a1701** [lin-ycv/EverythingPowerToys#64]
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/48874489/e4bdcddd-6d1a-43fe-a51c-3e71dcc53bea)

如图所示，在使用该插件搜索时，常常会搜到许多日志文件、预加载文件等。这些文件的名称往往与用户实际想要找的文件相似（如图，搜索 QQ 时会搜到 QQ 的数据库文件），且频繁修改，干扰排序，使用现有的排序策略经常无法有效的找到想要的文件。

希望增加一个扩展名白名单配置，这样用户就可以设置仅搜索常用类型的文件，而不会因这些临时文件而焦头烂额。

**Comment by lin-ycv** [comment]
如果是要白名單特定的檔案類型，可以用settings.toml 去做macro
