### ISSUE TITLE
[BUG] 使用Everything并关闭窗口后提示Everything未运行

### ISSUE THREAD

**Issue by Ptilopsis01** [lin-ycv/EverythingPowerToys#65]
**Describe the bug**
在使用了Everything软件并关闭了该窗口后，即使后台的Everything服务仍在运行，powertoys run依然会提示Everything未运行

**To Reproduce**
1. 使用everything
2. 关闭everything窗口
3. 启动powertoys run
4. 提示everything未运行

**Expected behavior**
如上所述，可正常使用拓展

**Screenshots**
everything设置如图：
<img width="362" alt="image" src="https://github.com/lin-ycv/EverythingPowerToys/assets/93318731/40887e05-1f06-4a58-aff4-f54639fced9c">

**Logs (please upload or provide link to you log):**
[2023-12-08.txt](https://github.com/lin-ycv/EverythingPowerToys/files/13608067/2023-12-08.txt)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.76.1
 - Everything: 1.4.1.1024(x64)
 - Windows: win11 22631.2792

**Additional context**

**Comment by lin-ycv** [comment]
這我無法重現，你之前是可以正常使用嗎? PowerToys 升級到 0.76.1 才這樣?
log裡是有看到一些錯誤，但都與everything無關

https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/7b1b8d5e-5a82-447f-8956-18064c605ac1
