### ISSUE TITLE
[BUG] Incompatible with powertoys v0.76

### ISSUE THREAD

**Issue by momsi** [lin-ycv/EverythingPowerToys#67]
Probably similat to #65 

The current version is incompatible to the new version of powertoys 0.76.
At the start of powertoys, the following message appears (translated from german to english):

Plug-Ins: Everything. The plug-in could not be loaded and was deactivated. Contact the developer of the plug-in.

**To Reproduce**
1. Start powertoys with plugin.

**Logs (please upload or provide link to you log):**
 I guess the relevant log entry is:
`
[2023-12-12 21:25:21.9602] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::190]
Can't validate plugin ID of plugin <Everything> in C:\Program Files\PowerToys\RunPlugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll: The static property <Main.PluginID> was not found.
`

**Version (please provide the version of software you are using):**
 - PowerToy: 0.76
 - Everything: 1.4.1.1024 (x64)
 - Windows: 11 22H2

**Comment by lin-ycv** [comment]
PluginID is implemented on the latest version of the plugin 0.75.1
I'm using the latest powertoys 0.76.1 just fine (tho I might be on a different variant than the release.)
Are you sure you are on the latest version of this plugin?

**Comment by momsi** [comment]
Oh man .... well i was very sure that I installed the latest version after updating PT and the error appeared.... I obviously must've made some mistake. I downloaded and tried again and now it's working .... sorry
