### ISSUE TITLE
Wrong install location

### ISSUE THREAD

**Issue by Youxikong** [lin-ycv/EverythingPowerToys#68]
Install location `%LOCALAPPDATA%\PowerToys\RunPlugins` written in readme is wrong. `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\` is true.

**Comment by lin-ycv** [comment]
@Youxikong 
I just did a fresh install using winget, `%LOCALAPPDATA%\PowerToys\RunPlugins` is the correct install location
`%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\` is where logs are stored, that shouldn't be where you put the plugin, which installation method did you use?
I've changed the readme back to `%LOCALAPPDATA%\PowerToys\RunPlugins`

**Comment by Youxikong** [comment]
It's confusing. I'm using version 0.77.0. In my computer, there is no directory `PowerToys` in `%LOCALAPPDATA%`, all Powertoys Run relative files are placed in `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run`, including Plugins.
And some other powertoys run plugins repository is also claiming `%LOCALAPPDATA%\PowerToys\RunPlugins` is the install location, like [PowerToys-Run-EdgeFavorite](https://github.com/davidegiacometti/PowerToys-Run-EdgeFavorite)

**Comment by lin-ycv** [comment]
Depending on the install method and how the plugin is developed, this all affects where the plugin should be installed.
Let me test this further and get back to you; do what works for you in the meantime.
