### ISSUE TITLE
Add ability to Set the shortcuts for the context menu

### ISSUE THREAD

**Issue by artistro08** [lin-ycv/EverythingPowerToys#69]
I never liked it that the shortcuts for the context menu are different than the default ones in explorer. I would like it to be the same to not have to memorize different shortcuts

You should create a setting to change the shortcuts. alternatively, it can just be a switch to swap the shortcuts for "Copy" and "Copy Path" 

I've tried moving them, which helps, but I always press "Ctrl+C" instead of "Ctrl+alt+C" since I use the explorer plugin and the everything plugin together

**Comment by lin-ycv** [comment]
not sure which version you're on, but recent versions already have these features in the settings
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/9d2f5e02-4921-4e90-b3ae-c8e895d3f369)

Does these options not work as expected?

**Comment by artistro08** [comment]
Ah. I misunderstood. I thought it was a setting to turn it on, not Swap the shortcuts. 

Thank you

**Comment by artistro08** [comment]
Ah. I misunderstood. I thought it was a setting to turn it on, not Swap the shortcuts. 

Thank you
