### ISSUE TITLE
[BUG] 过滤搜索时everything自带的过滤词不起作用

### ISSUE THREAD

**Issue by konglongbt** [lin-ycv/EverythingPowerToys#70]
比如我在搜索大于2mb的图片，输入关键词  **pic: size:>2mb** ，但是size:>2mb不起作用，在everything里搜索是可以的。我录了个屏
![screenshots](https://github.com/lin-ycv/EverythingPowerToys/assets/6247227/f0678fca-cce4-4f50-94ad-748dfe925c9f)
查看代码发现，应该是没有考虑有多个过滤条件的情况。

**Comment by lin-ycv** [comment]
解決了，但我先等 PT 0.77.0，確認沒問題再發布
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/63f494ae-34bf-4122-b1e5-966e5966b245)
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/092da337-3f12-4ec6-b0fb-fe30e38d22f2)
