### ISSUE TITLE
使用此插件搜索的结果要比使用everything搜索的结果要少很多，请教是我使用的问题还是插件本身的BUG?

### ISSUE THREAD

**Issue by yamaha68** [lin-ycv/EverythingPowerToys#71]
使用此插件搜索的结果要比使用everything搜索的结果要少很多，请教是我使用的问题还是插件本身的BUG?

**Comment by lin-ycv** [comment]
預設顯示前20個結果，在powertoys設定裡可以設定更多

**Comment by yamaha68** [comment]
感谢您的及时回复，但是问题好像不是显示的问题，您看一下我的截图：
![插件搜索](https://github.com/lin-ycv/EverythingPowerToys/assets/70887011/eaba6763-482c-480d-9380-9a79fec3e267)
![软件搜索](https://github.com/lin-ycv/EverythingPowerToys/assets/70887011/3cabe878-06f3-4ae8-8dac-7a785666af55)
![设置20](https://github.com/lin-ycv/EverythingPowerToys/assets/70887011/8db31a95-e9b4-404e-b7b3-97d9233bd301)

**Comment by lin-ycv** [comment]
Powertoys 內建功能 軟體收尋 “programs" 的啟動快捷是 `.`, 所以當你打 `.ttf` 他會認為你在收尋程式，收尋詞就不會被傳給everything.
將軟體收尋的快捷改成其他字元應該就可以來

**Comment by yamaha68** [comment]
我已更改为E
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/70887011/fd16c0de-d0ac-4142-8126-c2f215778fc4)

**Comment by yamaha68** [comment]
在搜索.ttf之前，我就已经修改为E，我是在这里 [https://www.weekweekapp.com/everything-win-search/](url)看到的推荐，也想推荐给大家，但是就是搞不明白为什么搜索结果少这么多

**Comment by lin-ycv** [comment]
我是說這個的快捷要改
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/6d742175-437e-44af-9d81-535de5a1cfd7)

**Comment by yamaha68** [comment]
明白，谢谢！
