### ISSUE TITLE
[BUG] fail to load plugin：everytime

### ISSUE THREAD

**Issue by a12b19** [lin-ycv/EverythingPowerToys#72]
hello： thank you plugin
i meet a error on start use everything plugin
1：i unzip the plugin zip and put them in RunPlugins folder under C:\Program Files\PowerToys\RunPlugins\Everything
2:i check the everything version is 1.4.1.1024。it a 64 install version
on restart powertoys。i meet this error fail to load plugin：everytime

**Comment by lin-ycv** [comment]
What version of powertoys and the plugin are you using?
Does the version number of the plugin match the number of the plugin?
And please provide logs if you're sure you installed the plugin correctly.

**Comment by TomShaw132** [comment]
Hi, I have the same issue post updating to the newer version of the plugin. Here are my logs.
I'll reinstall power toys as that is what is recommended in logs
[2024-01-04.txt](https://github.com/lin-ycv/EverythingPowerToys/files/13827058/2024-01-04.txt)

**Comment by TomShaw132** [comment]
uninstalling power toys, and removing all leftover powertoys. And reinstalling fixed the issue.

**Comment by lin-ycv** [comment]
As this seems to be a corrupt file issue and not a plugin issue, I'll be closing this.
