### ISSUE TITLE
[BUG] Wrong path in release

### ISSUE THREAD

**Issue by pilgrimlyieu** [lin-ycv/EverythingPowerToys#75]
**Describe the bug**
`%LOCALAPPDATA%\PowerToys\RunPlugins\` in recent releases should be `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins` according to [the official description](https://github.com/microsoft/PowerToys/blob/main/doc/thirdPartyRunPlugins.md).

> The recommended path for the plugins is `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins`.

The following is the original suggestion in release.

> Extract folder in the zip file to `C:\Program Files\PowerToys\RunPlugins`
> If you're using per user install (winget/Microsoft Store), you may need to extract it to `%LOCALAPPDATA%\PowerToys\RunPlugins\` instead

Some one may ignore the second choice, which is recommended for most of users and jump into the first choice then get bothered with Administrator rights.

As a result, I consider it would be better to modify the description making it the official suggestion the first choice. 

Relevant to #68.

**Comment by lin-ycv** [comment]
So this is something new, that file was created just last August. I was not aware they had recommended that directory folder.

It used to be that plugin folders had to go into very specific locations, or the dll references wouldn't work, I guess they made some improvements.

Instructions have been changed.

> side note:
installing to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins` does have a slight quirk tho.
In the Run settings, plugins are ordered "alphabetically" (based on the plugin folder name and not the displayed name).
Plugins in the recommended folder are loaded after the native folders, causing them to show up at the very bottom of the settings list, when I was testing this directory, I didn't see the Everything settings at the top, causing me to think it was not loaded.
