### ISSUE TITLE
[BUG] Turning off "Include in global result" option not working

### ISSUE THREAD

**Issue by maokwen** [lin-ycv/EverythingPowerToys#78]
**Describe the bug**
Turning off "Include in global result" option not working, Everything's result still in global results.
Only certain queries cause the problem, maybe the cache is not cleared?

**Screenshots**
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/18361388/90dbb2e4-4668-4e8e-96ec-82879aa68c27)

**Version (please provide the version of software you are using):**
 - PowerToy: 0.77.0.0
 - Everything: 0.77.0
 - Windows: Build 22631.3007 Windows Feature Experience Pack 1000.22681.1000.0

**Comment by konglongbt** [comment]
你设置的 f 激活搜索啊，你搜索 firefox 不就激活了吗，相当于搜索 irefox

**Comment by lin-ycv** [comment]
As @konglongbt pointed out, your activation key word is  `f` so when you search `firefox`, `f` activates the plugin and the query is `irefox`
This is why the default activation keyword is `` ` ``, it prevents accidental activations.
