### ISSUE TITLE
当 Everything 返回结果为空时请隐藏“Timed Out”的提示

### ISSUE THREAD

**Issue by xuangeyouneihan** [lin-ycv/EverythingPowerToys#8]
如题，我也不知道这是 Bug Report 还是 Feature Request，只希望隐藏最上面的“Timed Out”提示，插件设置页面已经勾选“Wait”。这个倒不影响正常使用，纯粹是不好看。谢谢！
![image](https://user-images.githubusercontent.com/50788434/159101200-151823ff-cc88-45d6-bef5-90eb3c31f552.png)
![image](https://user-images.githubusercontent.com/50788434/159101417-9f103cec-5f76-4eba-9db0-e52abd05337d.png)

**Comment by lin-ycv** [comment]
對 0562R1 做了修改，有已經有開wait就不會再提醒
請重新下載0562R1: [Everything0562_R1.zip](https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.56.2/Everything0562_R1.zip)

**Comment by xuangeyouneihan** [comment]
您好像忘上传到 Release 了，我在 Release 页面下载的依旧不管用，只有在这下载的管用
