### ISSUE TITLE
[BUG] Filters only work at the start of a search

### ISSUE THREAD

**Issue by AJolly** [lin-ycv/EverythingPowerToys#80]
Not sure if this is intended.  
If you put the filter at the start of the search it works.
exe: ping
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/91493/7ecdd99f-a610-41e8-9f73-d5cfc325af2b)

Anywhere else it doesnt, which I wasn't expecting.  
ping exe:
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/91493/8fda2a0e-774a-402f-a29e-5e06fe0e24aa)

**Comment by lin-ycv** [comment]
This is the intended behaviour for 0.77.0 as explained in the release change log
It has been fixed for the next version. Meanwhile, I believe filters in 0.76.0 works without this limitation 

![Screenshot_20240118_092432_Chrome](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/fa1f18a9-ae57-4052-985e-2a436c8aa143)
