### ISSUE TITLE
[BUG] 我无法使用winget安装

### ISSUE THREAD

**Issue by ZSXB2468** [lin-ycv/EverythingPowerToys#81]
我使用winget install lin-ycv.EverythingPowerToys安装时，winget报错4294967295
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/62994932/deb689a4-7e7f-4c21-98b4-babb72cbe526)

同时弹出火绒警报
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/62994932/61abd5e7-8c95-4ef2-9499-86d20f4936b0)

请问该如何应对？

**Comment by lin-ycv** [comment]
按信任，或改用手動安裝

**Comment by Cranyozen** [comment]
我这边也出现了这种情况，exe 报毒
能否考虑换回 zip,  或者向火绒反馈

**Comment by lin-ycv** [comment]
This is a false positive by AV programs, most likely because it is not code signed. If you have concerns, you can always fallback to downloading the zip file in the release section. 
這是誤判，主要應該是安裝檔沒有簽章。你有疑慮的話還是可以到發布頁面下載zip檔
https://github.com/lin-ycv/EverythingPowerToys/releases/latest
