### ISSUE TITLE
[Request] 发布到 Scoop

### ISSUE THREAD

**Issue by xuangeyouneihan** [lin-ycv/EverythingPowerToys#87]
**Is your feature request related to a problem? Please describe.**
并没有，也不是特别必要，只是觉得上了 [Chocolatey](https://chocolatey.org) 没上 [Scoop](https://scoop.sh) 有点遗憾

**Describe the solution you'd like**
将软件包发布到 [Scoop](https://scoop.sh) 的 [Main](https://github.com/ScoopInstaller/Main) 软件源（bucket）

**Describe alternatives you've considered**
将软件包发布到 [Scoop](https://scoop.sh) 的 [Extras](https://github.com/ScoopInstaller/Extras) 软件源或其他热门软件源

**Additional context**
[Criteria for including apps in the main bucket](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket)
[Contribution Guidelines](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)

**Comment by lin-ycv** [comment]
沒有用過Scoop需要一點時間研究，快速地看了了一下應該是沒問題
但最近比較忙沒有時間處理且測試這個，要等我有空研究json要怎麼寫
如果有人可以提供已經寫好的json會加速這個流程，我可以將他加到Action裡自動發布

**Comment by xuangeyouneihan** [comment]
在官网上搜索所有软件源倒是找到 @LuoHuiRu 的[软件源](https://github.com/LuoHuiRu/ScoopBucket)里有本插件的[json](https://github.com/LuoHuiRu/ScoopBucket/blob/master/bucket/PowerToys-Everything.json)，但是它如果没在scoop上安装powertoys的话就只能手动复制插件，您看看能不能再想想办法？

**Comment by lin-ycv** [comment]
https://github.com/ScoopInstaller/Extras/pull/12912

**Comment by xuangeyouneihan** [comment]
试了一下，感觉powertoys最好还是写suggests里，写depends里的话会在安装装插件之前自动安装powertoys，哪怕之前已经在scoop之外的地方安装过powertoys。另外，可以考虑下将插件用powershell软链接到powertoys的插件目录（[Create Symbolic Link in Windows 10 with PowerShell](https://winaero.com/create-symbolic-link-windows-10-powershell)），将settings.toml放到persist文件夹里以在升级时保留设置项，以及在全局安装（--global或-g）时将插件软链接到C:\Program Files\PowerToys\RunPlugins。除了第一点之外别的都不是特别要紧，麻烦考虑一下

**Comment by lin-ycv** [comment]
可以將PT移到suggest,但會有用scoop裝EPT卻手動裝PT的用戶嗎？我是有測到如果不是scoop安裝PT, scoop會再裝一次這個狀況，但我不確定有什麼實際影響，就只是需要多等一下它下載PT的時間？

Junction到current可以考慮，之後再測試;目前使用直接複製比照其它安裝方式的結果，之後有人碰到問題要除錯才不會有過多的變數要考慮

Settings.toml這個暫時不考慮,雖然他的功能不常改，但若有修改功能，我還要去寫邏輯決定處理內容版本不一樣的問題，我認為會修改toml的使用者是進階的使用者，他們自行管理toml檔案是合理的。如果你覺得像需要有這個功能，請開一個新的feature request.

**Comment by lin-ycv** [comment]
預計0.80.0會有更新
如果新版出來前scoop extra的PR一直不被接受，之後就不會再支援scoop

**Comment by xuangeyouneihan** [comment]
好家伙scoop extras的审核是真的慢

**Comment by xuangeyouneihan** [comment]
寄！
