### ISSUE TITLE
Missing entry in scoop

### ISSUE THREAD

**Issue by BerserkWolfS** [lin-ycv/EverythingPowerToys#89]
Hello, 

I tried to install the extension using scoop, but it was not listed in any buckets. It this installation method still available ?

Thanks for providing it anyway, this extension is super useful !!

BWolfS

**Comment by lin-ycv** [comment]
So I've pushed it so scoop, but it seems they've not accepted the PR yet.
I was under the impression that the review process would be relatively fast, so I added the instruction first. The PR is here:
https://github.com/ScoopInstaller/Extras/pull/12912

**Comment by BerserkWolfS** [comment]
Ok, so it looks like I will have to wait.
Thanks for the quick answer 👍 !

**Comment by lin-ycv** [comment]
Planning for a 0.80.0 release, if the PR doesn't get merged before than, I won't be support scoop, as it takes too long to be practical

**Comment by BerserkWolfS** [comment]
Ok, noted, I understand. Thank you very much for the update 🙂 !
