### ISSUE TITLE
[BUG] WinGet install fails

### ISSUE THREAD

**Issue by gabriel-vanca** [lin-ycv/EverythingPowerToys#92]
Tried to update to PowerToys via WinGet, but I encountered two issues:
1. The update fails if I try to use the `update` command. I get a `No installed package found matching input criteria.` error. Install only works with `install`. 
2. The install fails if PowerToys is not turned off. If PowerToys is not off, the installation runs successfully and it looks like everything is ok, but even after restarting the PC, the system still only sees the the old 0.78 install. On the other side, if I turn off PowerToys and then update, the system recognises the correct 0.80 version after restarting PowerToys.

I mentioned both these issues in the same bug report as I don't know whether they are related or not.

**Comment by lin-ycv** [comment]
Not sure what's causing these issues, I'll find time to investigate it. Winget should give an error if the install wasn't successful.

**Comment by lin-ycv** [comment]
1. made a incorrect configuration for update behavior, will be fixed for next release
2. forgot to set the exitcode on errors, so winget got sucess reply even on errors, will be fixed for next release
