### ISSUE TITLE
[BUG] Self-Extraction Installer install fails

### ISSUE THREAD

**Issue by xixiha5230** [lin-ycv/EverythingPowerToys#93]
**Describe the bug**

Show **error opening file for writing** when installing.

**To Reproduce**
1. Double click exe file
2. Click install 

**Expected behavior**
Installing normally

**Screenshots**
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/31526189/7620478a-ba55-47ef-ba20-5c94243748b6)

**Logs (please upload or provide link to you log):**
No logs generated

**Version (please provide the version of software you are using):**
 - PowerToy: 0.79.0
 - Everything: 0.80.0
 - Windows: Win11 23H2

**Additional context**
Maybe it's because there is a **space** between my username

**Comment by lin-ycv** [comment]
this is the same issue as #90 
previous versions of the installer automatically closes powertoys, but that behaviour gets caught by AV as malicous, so for this version I dropped that logic, meaning you have to close PowerToys manually before the install.

**Comment by xixiha5230** [comment]
I have an idea - if the user is detected to not have closed PowerToy, a pop-up prompt could be displayed to remind the user to close it. This could help avoid AV issues and not make the user think an error has occurred.

I understand this may add some work, but it's just a small suggestion. How to handle it is entirely up to you. Thank you for developing this useful plugin.

**Comment by lin-ycv** [comment]
Trying to deal with AV FP is complex, as each have their own logic, and can also change their detection triggers from time to time. Some AV will flag the act of process scaning as malicious while others won't.

I agree that it's not very well handled right now, I still need to do more tests to figure out the best way forward. Hopefuly this can be dealt with before the next release.
