### ISSUE TITLE
💡 winget DSC deployment

### ISSUE THREAD

**Issue by akamienski** [lin-ycv/EverythingPowerToys#98]
**Is your feature request related to a problem? Please describe.**
Plugin deployed with [PowerToys DSC deployment](https://learn.microsoft.com/en-us/windows/powertoys/dsc-configure) using winget.

**Describe the solution you'd like**
Either as winget PowerToys deployment, where I can define to install plugin as well, or seperately while installing Everything plugin with winget.

**Additional context**
I'd like to change default activation command and few other settings.

**Comment by lin-ycv** [comment]
Is there something I need to implement?
From what I can tell, DSC is handled by powertoys itself.

You have to create a YAML for the configurations that you want, and call that YAML using `winget configure` instead of `winget install`

**Comment by lin-ycv** [comment]
@akamienski can you provide more information? Does it currently not work? Can you provide your YAML file that you're using?
